[DLG-282] CloudWatch로 로그를 전송한다.
dailyge/dailyge-server pull request #148
Opened 2024-09-12 04:40 UTC by devjun10

## 📝 작업 내용

로그를 CloudWatch로 전송하는 작업을 했습니다. 

- [x] CloudWatch로 로그 전송
- [x] 비동기 설정 추가

<br/><br/>

로그에 순서를 추가해 조금 더 알아보기 편하도록 코드를 수정했습니다. 또한 기존에는 랜덤 UUID를 사용했는데, 로그에 추가작업을 하기 위해 Timebased UUID로 변경했습니다.

```shell
{"order":"1", "layer":"ENTRANCE", "path":"/api/health-check", "method":"GET", "traceId":"8866b9cd-70c0-11ef-ac4a-29b05d3793cc", "ip":"0:0:0:0:0:0:0:1", "visitor":{"userId":null,"role":"GUEST"}, "time":"2024-09-12T13:36:09.625", "duration":"0ms", "context":{"args":null, "result":null}}
{"order":"2", "layer":"APPLICATION", "path":"/api/health-check", "method":"GET", "traceId":"8866b9cd-70c0-11ef-ac4a-29b05d3793cc", "ip":"0:0:0:0:0:0:0:1", "visitor":{"userId":null,"role":"GUEST"}, "time":"2024-09-12T13:36:09.649", "duration":"0ms", "context":{"args":"[eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjY0NTAzMDMsInN1YiI6ImJmMmUyZDY0ZmRhNWQ4NTI5NTM0ZWM4YTdhYWNkNzgzMDRjMDJjZUBnbWFpbC5jb20iLCJpZCI6IlJXaXlYSGNwWGgvTFhtZFpZYmovelQvZmRnbWVjeGZUWkVnMk12aTE2cTQ9In0.sgZmLOO6QYMNyflPkM5Yv_vcHg_KRnUpXl2x2QtR-FA]", "result":null}}
{"order":"2", "layer":"APPLICATION", "path":"/api/health-check", "method":"GET", "traceId":"8866b9cd-70c0-11ef-ac4a-29b05d3793cc", "ip":"0:0:0:0:0:0:0:1", "visitor":{"userId":null,"role":"GUEST"}, "time":"2024-09-12T13:36:09.668", "duration":"19ms", "context":{"args":"[eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjY0NTAzMDMsInN1YiI6ImJmMmUyZDY0ZmRhNWQ4NTI5NTM0ZWM4YTdhYWNkNzgzMDRjMDJjZUBnbWFpbC5jb20iLCJpZCI6IlJXaXlYSGNwWGgvTFhtZFpZYmovelQvZmRnbWVjeGZUWkVnMk12aTE2cTQ9In0.sgZmLOO6QYMNyflPkM5Yv_vcHg_KRnUpXl2x2QtR-FA]", "result":false}}
{"order":"3", "layer":"PRESENTATION", "path":"/api/health-check", "method":"GET", "traceId":"8866b9cd-70c0-11ef-ac4a-29b05d3793cc", "ip":"0:0:0:0:0:0:0:1", "visitor":{"userId":null,"role":"GUEST"}, "time":"2024-09-12T13:36:09.677", "duration":"0ms", "context":{"args":"[]", "result":null}}
{"order":"3", "layer":"PRESENTATION", "path":"/api/health-check", "method":"GET", "traceId":"8866b9cd-70c0-11ef-ac4a-29b05d3793cc", "ip":"0:0:0:0:0:0:0:1", "visitor":{"userId":null,"role":"GUEST"}, "time":"2024-09-12T13:36:09.678", "duration":"1ms", "context":{"args":"[]", "result":{"headers":{},"body":{"code":200,"message":"OK","data":null},"statusCode":"OK","statusCodeValue":200}}}
{"order":"4", "layer":"ENTRANCE", "path":"/api/health-check", "method":"GET", "traceId":"8866b9cd-70c0-11ef-ac4a-29b05d3793cc", "ip":"0:0:0:0:0:0:0:1", "visitor":{"userId":null,"role":"GUEST"}, "time":"2024-09-12T13:36:09.691", "duration":"65ms", "context":{"args":null, "result":null}}
```

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-282)

2024-09-12 05:01 UTC, kmularise approved these changes
로그 전송 기능 확인했어요! 실서버에서 로그를 보기 더 편리해지겠네요! 고생하셨어요!

2024-09-12 05:03 UTC, kmularise requested changes
로그 전송 기능 확인했어요! 실서버에서 로그를 더 편리하게 볼 수 있겠네요! 고생하셨습니다. 수정할 부분만 확인되면 머지하면 될거 같아요!

2024-09-12 05:05 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +    private static final String LOG_GROUP = "dailyge-ol";
현재는 dailyge-ol로 구분하는데, 생각해보니 개발/상용 두 개를 구분해야 할 것 같네요. dailyge-dev-ol, dailyge-prod-ol 두 그룹으로 분리하겠습니다.

> ol은 operation log의 약자 입니다.

2024-09-12 05:05 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +    private static final CachingDateFormatter dateFormatter = new CachingDateFormatter("yyyy-MM-dd");
현재는 dailyge-ol로 사용하는데, 생각해보니 개발/상용 두 개를 구분해야 할 것 같네요. dailyge-dev-ol, dailyge-prod-ol 두 그룹으로 분리하겠습니다.

> ol은 operation log의 약자 입니다.

2024-09-12 05:05 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +    public CloudWatchLogAppender() {
아래와 같이 생성자를 호출하는 부분이 있어 public으로 뒀습니다. 

```java
final CloudWatchLogAppender appender = new CloudWatchLogAppender( );
```

2024-09-12 05:06 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +        final SdkEventLoopGroup sdkEventLoopGroup = SdkEventLoopGroup.create(new NioEventLoopGroup(5));
혹시 그렇게 하려는 의도가 있을까요?

2024-09-12 05:07 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +    protected void append(final ILoggingEvent event) {
비동기로 로그를 전송해야 해서 그렇습니다. 로그를 동기로 전송하면, 응답 속도가 느려지기 때문이여요. 

> 처음에 동기로 전송하니, 헬스 체크를 할 때도 0.4~0.5초가 나왔네요.

2024-09-12 05:08 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/web/WebConfiguration.java
> +    public RequestContextFilter requestContextFilter() {
비동기로 로그를 전송하면 MDC Filter에서 문맥을 읽지 못해서 이를 읽는데 사용합니다.

2024-09-12 05:10 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/LoggingConfig.java
> +        asyncAppender.setDiscardingThreshold(0);
한 번 들어오면 로그가 적게는 4~5개에서 많으면 10개 이상도 쌓이는데, 현재 저희 쓰레드 풀 개수가 300~350개 입니다. 그래서 한 번에 10개가 남는다는 가정하에, (3000~3500)x2 정도에 추가로 1000개를 더 두면 적절하지 않을까 했는데, 조금 과한 것 같기도 하네요? 몇 개가 적당해 보이시나요?

> setDiscardingThreshold(0) 는 로그를 버리지 않겠다는 설정입니다.

2024-09-12 05:12 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/LoggingConfig.java
> +        asyncAppender.setDiscardingThreshold(0);
한 번 사용자 요청이 오면, 로그가 **적게는 4~5개**, 많은 경우 10개 이상도 쌓입니다. 현재 저희 쓰레드 풀 개수가 **300~350개** 인데, 한 번에 10개가 남는다는 가정하에, (3000~3500)x2 + 추가 1000개를 더 두면 적절하지 않을까 했습니다. 적고보니 조금 과한 것 같기도 하네요? 몇 개가 적당해 보이시나요?

> setDiscardingThreshold(0) 는 로그를 버리지 않겠다는 설정입니다.

2024-09-12 05:13 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +    private static final String LOG_GROUP = "dailyge-ol";
현재는 dailyge-ol로 사용하는데, 생각해보니 개발/상용 두 개를 구분해야 할 것 같네요. dailyge-dev-ol, dailyge-prod-ol 두 그룹으로 분리하겠습니다.

> ol은 operation log의 약자 입니다.

2024-09-12 05:13 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +    private static final CachingDateFormatter dateFormatter = new CachingDateFormatter("yyyy-MM-dd");
로그 그룹은 날짜로 구분하고, 내부에 시간은 별도로 기록합니다. 저건 폴더 개념이라고 보시면 돼요. 즉, 폴더 별로 로그가 저장되는거죠. 그 기준이 날짜고요.

2024-09-12 05:14 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeUser.java
> +    public static DailygeUser getDailygeUser(final Object obj) {
객체 내부에 로직을 두면 유지 보수하기가 편하고, 테스트 작성도 쉬워서 그렇습니다. 적고보니 테스트 깜빡했네요 ㅋㅋ

2024-09-12 05:15 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeUser.java
> +    public static DailygeUser getDailygeUser(final Object obj) {
객체 내부에 로직을 두면 유지 보수하기가 편하고, 테스트 작성도 쉬워서 그렇습니다. 적고보니 테스트 깜빡했네요 ㅋㅋ

2024-09-12 05:39 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeUser.java
> +    public static DailygeUser getDailygeUser(final Object obj) {
try 구문에서 예상되는 exception이 있나요?

2024-09-12 05:39 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +    public CloudWatchLogAppender() {
해당 생성자가 쓰이는 곳이 같은 패키지인 것으로 보이는데요.
그러면 접근 제어자는 최대한 보수적으로 가져가는게 좋을거라 생각해서 public 대신 default는 어떠신가요?

2024-09-12 05:39 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +        final SdkEventLoopGroup sdkEventLoopGroup = SdkEventLoopGroup.create(new NioEventLoopGroup(5));
해당 값들이 변경이 될 때 소스코드를 고쳐야 되기 때문이라고 생각했는데요. 변경될 가능성이 없다면 이대로 가는 것도 괜찮을 거 같아요!

2024-09-12 05:39 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/LoggingConfig.java
> +        asyncAppender.setDiscardingThreshold(0);
스레드 풀 개수, 요청당 로그, accept-count에 따라서 그렇게 설정하신 거군요! 그렇다면 일단 저렇게 설정하면 좋을 거 같아요! 추후에 모니터링해보면서 조정하면 좋을 거 같아요!

2024-09-12 06:09 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeUser.java
> +    public static DailygeUser getDailygeUser(final Object obj) {
올바르지 않은 타입이 들어가면 **`ClassCastException`** 정도 있겠네요. 구체적인 예외로 변경할게요.

2024-09-12 06:13 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeUser.java
> +    public static DailygeUser getDailygeUser(final Object obj) {
올바르지 않은 타입이 들어가면 **`ClassCastException`** 정도 있겠네요. 구체적인 예외로 변경할게요.

2024-09-12 07:05 UTC, management-supporter approved these changes

2024-09-12 07:05 UTC, kmularise approved these changes

2024-09-12 07:09 UTC, management-supporter approved these changes

2024-09-12 07:09 UTC, kmularise approved these changes

2024-09-12 07:25 UTC, merged

2024-09-12 07:28 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
> +    public CloudWatchLogAppender() {
반영 완료!

2024-09-13 03:35 UTC, beatmeJY commented
제가 하루 비번인 동안 @kmularise 님께서 이미 많이 물어봐주셔서 이해하는데 도움이 되었네요.
AWS를 이용한 로깅은 처음보는데 기대가 되네요. 구현하시느라 고생많으셨습니다!👍🏻