[DLG-273] 쿠폰 당첨자를 선정하는 API를 개발한다.
dailyge/dailyge-server pull request #155
Opened 2024-09-13 11:56 UTC by kmularise

## 📝 작업 내용

쿠폰 당첨자를 선정하는 API를 개발했습니다.

- [X] 쿠폰 당첨자 선정 알고리즘
- [X] Redis에서 등록된 쿠폰 발급 신청 정보들 호출 및 제거

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-273)

2024-09-14 07:29 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventWriteDao.java
> +                long count = Long.parseLong(new String(queueCountBytes, StandardCharsets.UTF_8));
final 이 빠졌네요

2024-09-14 07:29 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventReadDao.java
> +            byte[] queueCountBytes = redisTemplate.opsForValue().get(QUEUE_COUNT_KEY);
final 이 빠졌네요

2024-09-14 07:29 UTC, beatmeJY commented on admin-api/src/main/java/project/dailyge/app/coupon/persistence/CouponEventReadDao.java
> +            byte[] queueCountBytes = redisTemplate.opsForValue().get(QUEUE_COUNT_KEY);
final 이 빠졌네요

2024-09-14 07:29 UTC, beatmeJY commented on admin-api/src/main/java/project/dailyge/app/coupon/presentation/request/CouponWinnerRequest.java
> +    Long couponCategoryId
개행이 필요할 것 같네요.

2024-09-14 07:29 UTC, beatmeJY commented on admin-api/src/main/java/project/dailyge/app/coupon/persistence/CouponEventWriteDao.java
> +                byte[] queueCountBytes = redisTemplate.opsForValue().get(QUEUE_COUNT_KEY);
final 키워드가 빠졌군요

2024-09-14 07:29 UTC, beatmeJY commented on admin-api/src/main/java/project/dailyge/app/coupon/persistence/CouponEventReadDao.java
> +    public List<CouponCache> findBulksByLimit(final int queueNumber, final int limit) {
개행이 필요할 것 같아요!

2024-09-14 07:29 UTC, beatmeJY commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/WinnerSelectAlgorithm.java
> +    private static List<Long> findSmallestElements(List<List<CouponCache>> couponEvents, int limit, PriorityQueue<CouponNode> minHeap) {
final 키워드랑 개행이 필요할 것 같습니다!

2024-09-14 07:29 UTC, beatmeJY commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/CouponService.java
> +    public List<Long> findWinners(final int winnerCount, final Long couponCategoryId) {
개행이 필요할 것 같습니다!

2024-09-14 07:38 UTC, beatmeJY commented on storage/memory/src/main/java/project/dailyge/core/cache/coupon/CouponCacheWriteRepository.java
>      void saveBulks(final List<CouponCache> couponCaches);
interface에서는 final 빠져도 좋을 것 같네요

2024-09-14 13:26 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventWriteDao.java
> +                long count = Long.parseLong(new String(queueCountBytes, StandardCharsets.UTF_8));
수정할게요!

2024-09-14 13:26 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventReadDao.java
> +            byte[] queueCountBytes = redisTemplate.opsForValue().get(QUEUE_COUNT_KEY);
수정할게요!

2024-09-14 13:28 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/persistence/CouponEventReadDao.java
> +            byte[] queueCountBytes = redisTemplate.opsForValue().get(QUEUE_COUNT_KEY);
수정할게요!

2024-09-14 13:36 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/presentation/request/CouponWinnerRequest.java
> +    Long couponCategoryId
이건 몰랐네요. 수정하겠습니다!

2024-09-15 01:00 UTC, kmularise commented on storage/memory/src/main/java/project/dailyge/core/cache/coupon/CouponCacheWriteRepository.java
>      void saveBulks(final List<CouponCache> couponCaches);
수정할게요!

2024-09-15 05:32 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/persistence/CouponEventReadDao.java
> +    public List<CouponCache> findBulksByLimit(final int queueNumber, final int limit) {
수정할게요!

2024-09-15 05:36 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/persistence/CouponEventWriteDao.java
> +                byte[] queueCountBytes = redisTemplate.opsForValue().get(QUEUE_COUNT_KEY);
수정할게요!

2024-09-15 05:36 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/WinnerSelectAlgorithm.java
> +    private static List<Long> findSmallestElements(List<List<CouponCache>> couponEvents, int limit, PriorityQueue<CouponNode> minHeap) {
수정할게요!

2024-09-15 05:38 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/CouponService.java
> +    public List<Long> findWinners(final int winnerCount, final Long couponCategoryId) {
수정할게요!

2024-09-15 09:22 UTC, devjun10 requested changes

2024-09-15 09:22 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventReadDao.java
> +    }
이러면 모든 쿠폰을 애플리케이션 메모리에 올리는거 아닌가요?

2024-09-15 09:24 UTC, devjun10 requested changes

2024-09-15 09:24 UTC, devjun10 commented on admin-api/src/test/java/project/dailyge/app/test/coupon/unittest/WinnerSelectionAlgorithmUnitTest.java
> +    }
이거 생성할 때, timestamp가 겹치는 사람들은 어떤 방식으로 정렬할지 정하셨나요? 물론 거의 안 겹치겠지만, 정책 세우셨는지 궁금해서 여쭤봅니다.

2024-09-15 09:26 UTC, devjun10 requested changes

2024-09-15 09:26 UTC, devjun10 commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/CouponService.java
> +        return userIds;
한 번에 반환할 수 있지 않을까요?

2024-09-15 09:26 UTC, devjun10 commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/WinnerSelectAlgorithm.java
> +                final CouponCache firstCoupon = currentQueue.get(0);
지금 로직이 각 그룹의 첫 번째 원소를 담는거 맞나요?

2024-09-15 09:27 UTC, devjun10 commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/WinnerSelectAlgorithm.java
> +                final CouponCache firstCoupon = currentQueue.get(0);
그리고 인덱스에 직접 접근하는건 조금 위험하지 않을까요?

2024-09-15 09:35 UTC, devjun10 commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/WinnerSelectAlgorithm.java
> +                final CouponCache firstCoupon = currentQueue.get(0);
Queue에다가 적정 갯수 만큼 옮겨 담고, 다시 앞에서 x개를 추린 후 나머지를 버리면, 직접 인덱스를 사용하지 않아도 될 것 같은데, 어떻게 생각하시나요? 

<br/>

예시를 들면 이해하기 편할 것 같은데, 현재 하나의 이벤트 참여 그룹에 100개씩 사용자 PK가 저장 돼 있다고 가정해볼게요. 당첨자는 10명만 추리고요.

```text
EventGroup1: [1,2,3,4,5,6,7,8,9,10 ... 99, 100]
EventGroup2: [101, 102,            .....          200]

......
```

<br/><br/>

우선순위 큐를 사용하고 있기 때문에 EventGroup1을 우선순위 큐에 모두 담으면 자동으로 정렬이 발생하겠죠? 빨리 참여한 사람 순서대로요. 그러면 앞에서 10명만 남기고 나머지 90명은 삭제하는거에요. 다음은 EventGroup2를 우선순위 큐에 모두 담고, 정렬이 발생한 후, 또 먼저 신청한 당첨자 10명만 남기는거죠. 이런 식으로 반복하면 인덱스에 직접 접근하지 않고도 효율적으로 처리할 수 있지 않을까요? 대략 아래와 같이요.

```java
public static void main(String[] args) {
        final PriorityQueue<CouponEventParticipant> queue = new PriorityQueue<>();
        final List<List<CouponEvent>> couponEvents = ....
        final int totalSize = couponEvents.size();
        final int start = 0 ;
        while(start<totalSize){
            final List<CouponEvent> eventGroup = couponEvents.get(start);
            // 모두 추가
            queue.addAll(eventGroup);
            
            // 앞에서 10개만 남긴 후 나머지 제거
        }
    }
```

2024-09-15 09:41 UTC, devjun10 commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/WinnerSelectAlgorithm.java
> +                final CouponCache firstCoupon = currentQueue.get(0);
물론 위 로직도 인덱스에 접근하기 때문에 차라리 레디스에 EventGroup을 key로 하나씩 조회한 후, 큐에 넣고 정렬, 처리하면 어떨까 싶네요.

> 레디스에 EventGroup1 조회 -> 우선순위 큐에 넣고 정렬 -> 먼저 신청한 사람 선정 -> 레디스에 EventGroup2 조회 ...

2024-09-16 01:57 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/persistence/CouponEventReadDao.java
> +            Objects.requireNonNull(redisTemplate.opsForValue().get(getKey(queueNumber))),
null을 반환하면 빈리스트를 반환하면 될거 같아요! 이 부분은 수정할게요!

2024-09-16 01:59 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/persistence/CouponEventWriteDao.java
> +                redisTemplate.opsForValue().set(COUPON_KEY, "\0".getBytes());
쿠폰 발급 참여 정보를 초기화시켜야 해서, bitmap에 대응하는 string을 초기화시키려고 했습니다!

2024-09-16 04:48 UTC, kmularise commented on admin-api/src/test/java/project/dailyge/app/test/coupon/unittest/WinnerSelectionAlgorithmUnitTest.java
> +    }
현재 테스트케이스에서는 timestamp가 겹치는 경우는 고려하지 않은 것 같습니다. 만약 timestamp가 겹치는 경우가 있다면, 정렬 기준은 따로 설정하지 않고 Java에서 구현된 우선순위큐의 기준에 따라 갈 것 같습니다. timestamp가 같은 경우를 고려하여 쿠폰 수량을 초과한 경우에는 쿠폰을 발급하지 않는 것으로 결정했습니다. 그 이유는 쿠폰 수량을 원래 의도대로 한정시키는 것이 더 중요하다고 생각했기 때문입니다.

2024-09-16 04:52 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventReadDao.java
> +    }
맞습니다. 쿠폰 발급 신청 데이터 10만개 정도로 생각했을 때, 그 정도는 애플리케이션 메모리에 올려도 괜찮다고 생각했던 거 같아요. 좀 더 최적화를 하자면 각 쿠폰 발급 데이터 묶음들이 저장되어 있는 Redis 값에서 쿠폰 당첨자수만큼만 가져오는 방식으로 진행할 수 있을 것 같습니다.

2024-09-16 04:52 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/CouponService.java
> +        return userIds;
수정할게요!

2024-09-16 04:53 UTC, kmularise commented on admin-api/src/main/java/project/dailyge/app/coupon/application/service/WinnerSelectAlgorithm.java
> +                final CouponCache firstCoupon = currentQueue.get(0);
네 인덱스에 접근하는 건 리스트 구현체가 LinkedList라면 문제가 있을거 같아요! 이부분은 수정하겠습니다.

2024-09-26 11:32 UTC, closed without merging