[DLG-315] 쿠폰 이벤트 참여 묶음 처리하는 백그라운드 작업을 스케줄러로 처리한다.
dailyge/dailyge-server pull request #170
Opened 2024-09-17 15:35 UTC by kmularise

## 📝 작업 내용

기존의 쿠폰 이벤트 참여 데이터들을 처리하는 백그라운드 작업을 스케줄러로 등록합니다. 이때 유동적으로 스케줄러 실행 및 중지, 실행 주기를 제어하기 위해 SchedulerExecutorService를 활용했습니다.

- [X] 스케줄러 시작 API 개발
- [X] 스케줄러 정지 API 개발

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-315)

2024-09-18 06:31 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/scheduler/CouponBulkScheduler.java
> +    }
CouponBulkScheduler가 CouponCacheWriteUseCase를 알고 있을 필요가 있을까요? Runnable로 의존성을 덜어낼 수 있지 않을까요?

2024-09-18 06:32 UTC, devjun10 requested changes

2024-09-18 06:32 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/scheduler/CouponBulkScheduler.java
> +            throw CommonException.from(CommonCodeAndMessage.SERVICE_UNAVAILABLE);
현재 서버 앞단에 로드 밸런서가 존재하는데, 중복 작업 처리를 위한 별도의 장치가 필요하지 않을까요?

2024-09-18 10:20 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/scheduler/CouponBulkScheduler.java
> +    }
좋은 의견입니다! 수정할게요.

2024-09-18 12:59 UTC, devjun10 requested changes
이거 동시성 테스트 작성 돼 있나요? 이 부분 아직 체크 못해봐서 조금 애매하네요.

2024-09-19 06:45 UTC, devjun10 approved these changes
수고하셨습니다. 스케줄러 제어할 때, API로 관리하는 부분 설명드거 잘 이해하신 것 같네요. 멀티 서버일 때는 API로만 컨트롤 하는게 힘든데, 나중에는 RabbitMQ같은 기술로 **`전체 스케줄러를 스위치처럼 껏다 켰다`** 할 수 있으면 더 좋을 것 같습니다.

2024-09-19 06:45 UTC, merged

2024-09-19 07:13 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponSchedulerApi.java
> +    }
`ResponseEntity` 대신 현재 저희 프로젝트에서 사용하고 있는 `ApiResponse`를 사용해보는 건 어떨까요?👀

2024-09-19 07:15 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/scheduler/CouponBulkScheduler.java
> +    public synchronized void startFixedTask(final int period, Runnable runnable) {
요고 개행하고 final 있으면 좋을 것 같네요!

2024-09-19 07:41 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponSchedulerApi.java
> +    }
[다음 PR](https://github.com/dailyge/dailyge-server/pull/175)에서 반영할게요!