[DLG-324] User 정보 조회 시 ID 대신 쿠키의 JWT로 조회한다.
dailyge/dailyge-server pull request #180
Opened 2024-09-20 11:33 UTC by beatmeJY

## 📝 작업 내용

JWT 쿠키가 암호화 및 ReadOnly 쿠키로 변경됨에 따라 클라이언트에서는 UserId를 알 수 없기 때문에,
기본 User 정보 조회 시 PathVariable로 받던 ID를 대신 쿠키로 조회하도록 수정하였습니다.

- [X] 쿠키의 JWT로 User 정보 조회

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-324)

2024-09-22 13:17 UTC, devjun10 requested changes

2024-09-22 13:17 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/UserReadApi.java
> +        final UserCache findUser = userCacheReadUseCase.findById(dailygeUser.getUserId());
ArgumentResolver에서 레디스에 사용자를 조회하면, 거기서 바로 반환하는게 더 빠르지 않을까요? 있는지 한 번 조회하고 서비스에 가서 다시 한 번 조회하면 두 번 조회하는 것 같네요. 

1. ArgumentResolver에서 캐시 조회
2. 컨트롤러로 온 후, 서비스로 가서 다시 캐시 조회

2024-09-22 13:35 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/UserReadApi.java
> +        final UserCache findUser = userCacheReadUseCase.findById(dailygeUser.getUserId());
좋은 것 같습니다 수정해볼게요!

2024-10-31 23:36 UTC, devjun10 commented
@beatmeJY 너무 오래 전 PR로 변경 사항이 많아 Closed 하겠습니다.

2024-10-31 23:36 UTC, closed without merging