[DLG-334] Task 월간 리포트 조회 API를 개발한다.
dailyge/dailyge-server pull request #189
Opened 2024-09-25 06:56 UTC by beatmeJY

## 📝 작업 내용

Task 월간 리포트 조회 API를 개발하였습니다.

통계 시에는 성공 미완료 개수만 필요하기에 Task에 필수적으로 필요한 컬럼 값만(Date, status) 조회하여 DTO로 가져오도록 하였습니다.

- [X] Task 월간 리포트 조회 API 개발
- [ ] 테스트 코드 작성

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-334)

2024-09-28 11:59 UTC, devjun10 requested changes

2024-09-28 11:59 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyTasksStatisticResponse.java
> +    private double[] currentMonthlyStatistic;
리스트가 아닌 배열을 사용한 이유가 있을까요? 

> EffectiveJava에 보면 배열 대신 리스트를 사용하라는 말이 나와요.

2024-09-28 11:59 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyTasksStatisticResponse.java
> +    }
DTO는 데이터를 전달하는 오브젝트인데, 이렇게 연산을 넣으면 재활용성이 떨어지지 않을까요? 

> 간단한 데이터 변환은 넣을 수 있지만, 여긴 로직이 들어간 것 같네요.

2024-09-28 11:59 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/TaskAchievementRank.java
> +        for (TaskAchievementRank rank : TaskAchievementRank.values()) {
final 키워드가 빠진 것 같아요.

2024-09-28 11:59 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/TaskAchievementRank.java
> +    private int rankNumber;
rank도 등급을 나타내기 충분하지 않나요? ㅎㅎ

2024-09-28 12:00 UTC, devjun10 requested changes

2024-09-28 12:00 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyTasksStatisticResponse.java
> +        final double... targetStatistic
저도 처음에 헷깔렸는데 IDE가 잡아주더라고요. 여튼 👍

2024-09-28 13:04 UTC, kmularise reviewed
:고생하셨어요! 리뷰 확인 부탁드려요 :)

2024-09-28 13:04 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
> +            int weekOfMonth = getWeekOfMonth(date) == 0 ? 1 : getWeekOfMonth(date);
final이 빠졌어요!

2024-09-28 13:04 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
> +            int weekOfMonth = getWeekOfMonth(date) == 0 ? 1 : getWeekOfMonth(date);
삼항 연산자를 사용하신 이유가 있나요? 삼항연산자 대신 getWeekOfMonth 내부에서 처리해도 괜찮을거 같아요!

2024-09-29 02:22 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/TaskAchievementRank.java
> +    private int rankNumber;
그리고 final을 사용하지 않은 이유가 있을까요?

2024-09-30 02:17 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
>          Assertions.assertTrue(tasks.size() > 0);
메서드 명을 리팩토링하면서 수정한 케이스라 제가 작성한 테스트 코드는 아니였네요.

하지만 static import와 task의 내부 필드를 상세하게 비교하는 건 좋은 수정사항이니 반영하겠습니다!👍🏻

2024-09-30 02:41 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyTasksStatisticResponse.java
> +    private double[] currentMonthlyStatistic;
성능상 조금 더 빠르지 않을까 생각하여 사용했는데, 저도 이전에 EffectiveJava 2에서 봤던 것 같네요 감사합니다 수정해둘게요!

2024-09-30 02:42 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyTasksStatisticResponse.java
> +    }
한 곳에서 관리하기 좋게 일급컬렉션 쪽으로 옮겨 놓겠습니다!

2024-09-30 03:26 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
> +            int weekOfMonth = getWeekOfMonth(date) == 0 ? 1 : getWeekOfMonth(date);
감사합니다! 좋은 것 같아요😀

2024-09-30 03:26 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/task/TaskAchievementRank.java
> +    private int rankNumber;
모두 수정하겠습니다! ㅎㅎ

2024-10-01 21:33 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
> +        final TaskJpaEntity findTask = tasks.getTaskEntities().get(0);
Tasks는 일급 컬렉션 테스트인데 왜 get(0)으로 인덱스에 접근해서 구체적인 데이터의 테스트를 하셨나요?

2024-10-01 21:36 UTC, devjun10 commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/TasksUnitTest.java
>      }
조금 오래 돼서 가물가물한데, 제가 특정 케이스 **`각각`** 에 대해 테스트 한다고 beforeEach를 사용하지 않았던 것으로 기억하는데, beforeEach로 모든 조건을 다 동일하게 만든 이유가 있을까요? 

> Task 개수가 소숫점인 경우와 같이 다양한 케이스가 있는데, 이렇게 모든 조건을 매 번 동일하게 맞출 필요가 있을까? 에 대한 질문입니다.

2024-10-01 21:37 UTC, devjun10 commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/TasksUnitTest.java
> +    }
빈 배열을 반환하나요? 리스트를 반환하나요?

2024-10-01 21:37 UTC, devjun10 commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/TasksUnitTest.java
> +        int weekOfMonth = getWeekOfMonth(week);
final이 빠진 것 같네요.

2024-10-01 21:48 UTC, devjun10 requested changes

2024-10-01 21:48 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeeksRateResponse.java
> +        }
데이터베이스에서 데이터를 조회했을 때, 결과가 없으면 빈 리스트를 반환하지 않나요?

2024-10-01 21:48 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeeksRateResponse.java
> +        }
null 체크를 왜 하신걸까요?

2024-10-01 21:48 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/TaskAchievementRank.java
>          for (TaskAchievementRank rank : TaskAchievementRank.values()) {
여기 final 키워드가 빠진 것 같네요.

2024-10-01 21:48 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
>          return taskEntities.stream().filter(task -> task.getDate().getMonth() == monthLocalDate.getMonth())
이거 디미터의 법칙 적용해보면 어떨까요?

2024-10-01 21:48 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +            rankCounts.set(achievementRank, rankCounts.get(achievementRank) + 1);
rankCounts.set으로 구체적인 배열에 접근해서 데이터를 처리하고 있는데, 이렇게 하신 이유가 있을까요? Index에 직접 접근하면 Index 범위 예외가 항상 따라오는데, 다른 방법은 없을까요?

```java
public class ArrayList<E> extends AbstractList<E>
        implements List<E>, RandomAccess, Cloneable, java.io.Serializable
{
    ......

    public E set(int index, E element) {
        Objects.checkIndex(index, size);
        E oldValue = elementData(index);
        elementData[index] = element;
        return oldValue;
    }

    ......

}
```

2024-10-01 21:52 UTC, devjun10 requested changes
전반적으로 코드는 많이 개선된 것 같은데, 배열이나 인덱스에 직접 접근하는 방식은 위험한 것 같아요. 이 부분 수정되면 좋을 것 같습니다. 

> 그리고 DTO에 로직을 안 넣는 것에 대해 간략히 설명드린 것 같은데, 본인이 생각하기에 일급 컬렉션이 더 좋은 이유에 대해 한 두 문장으로 정리해서 댓글 달아주면 좋을 것 같습니다. 😃

2024-10-01 21:54 UTC, devjun10 requested changes
추가로 [소나 클라우드](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&pullRequest=189&id=dailyge_dailyge-server) 보면 코드 스멜 경고 띄우는데, 이 부분도 수정해주세요.

2024-10-02 00:28 UTC, devjun10 requested changes

2024-10-02 00:28 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
>          }
index에 직접 접근하는 것 같은데, 다른 방법은 없을까요?

2024-10-02 00:28 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyTasksStatisticResponse.java
>          calculate(tasks);
왜 위에서는 HashMap을 new로 생성하고 밑에서 calculate로 초기화를 하신걸까요? 각각이 반환 값을 가지면 조금 더 명확하게 처리할 수 있지 않나요? 

> 지금 구조에서는 calculate하나에서 두 개를 초기화 하고 있는 것 같네요.

2024-10-02 00:29 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
> +            final List<TaskJpaEntity> currentMonthTask = currentMonthlyWeekTaskMap.getOrDefault(i, emptyList());
사소한데, List 자료구조면 복수형이 더 적절하지 않나요?

2024-10-02 00:29 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeeksRateResponse.java
> +    }
여기서 학습 하나 하고 가죠. 왜 private 생성자를 넣으신거에요?

2024-10-02 00:32 UTC, devjun10 commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/TasksUnitTest.java
> +    }
동일한 테스트가 두 개 있는거 아닌가요?

> @DisplayName("Tasks가 비어있을 경우 빈 그룹을 반환 한다.")

2024-10-02 00:44 UTC, devjun10 requested changes

2024-10-02 00:44 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final Double lastRank = 100.0 - monthlyRanks.stream().mapToDouble(Double::doubleValue).sum();
여기서 합치는 부분은 별도의 메서드로 추출할 수 있지 않을까요?

2024-10-02 00:44 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final BigDecimal roundedLastRank = new BigDecimal(lastRank).setScale(2, RoundingMode.HALF_UP);
BigDecimal을 사용하셨는데, 왜 반올림을 사용하셨을까요?

2024-10-02 00:44 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final BigDecimal roundedLastRank = new BigDecimal(lastRank).setScale(2, RoundingMode.HALF_UP);
그리고 BigDecimal을 왜 사용하셨을까요? 현재 구조에서 Double로 처리가 안 되는 부분이 있었을까요?

2024-10-02 00:44 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +    }
한 주는 7일인데, **`WeekFields.of(DayOfWeek.MONDAY, 4)`** 에서 4로 설정한 이유가 있을까요? 

> 이거 혹시 알고 사용하신거 맞을까요? 이전에 java.time 모듈 중 동작 원리 설명 못한 경우가 있어서 한 번 여쭤봐요. 👀

2024-10-02 00:46 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final Double lastRank = 100.0 - monthlyRanks.stream().mapToDouble(Double::doubleValue).sum();
그리고 이 부분은 왜 for문을 반대로 적용하셨을까요?

2024-10-02 00:48 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final BigDecimal roundedLastRank = new BigDecimal(lastRank).setScale(2, RoundingMode.HALF_UP);
Double은 왜 원시형이 아닌 래퍼형을 사용하셨나요?

2024-10-02 00:51 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeeksRateResponse.java
> +    }
이거 달면 또 하루 지날 것 같아서 별도의 PR이나 Discussion으로 정리 부탁드려요!

2024-10-02 02:14 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
>          }
그리고 i가 한 주를 의미하는 것 같은데, week로 표현하면 조금 더 가독성 있지 않을까요?

2024-10-02 03:03 UTC, beatmeJY commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/TasksUnitTest.java
> +    }
리스트를 반환하네요 수정하겠습니다!

2024-10-02 03:17 UTC, beatmeJY commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/TasksUnitTest.java
> +    }
해당 테스트는 서로 다른 테스트입니다! 테스트 명은 제가 조금 더 구분해두겠습니다!

2024-10-02 06:45 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +    }
한국에서는 목요일이 포함되어있어야 한 주의 시작이라고 볼 수 있습니다.
따라서 4로 설정하여 목요일이 포함되도록 설정한 것 입니다.

2024-10-02 06:49 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final BigDecimal roundedLastRank = new BigDecimal(lastRank).setScale(2, RoundingMode.HALF_UP);
위 계산 과정에서 결과값에 부동 소수점이 발생하여 없애기 위해 사용하였는데 더 간단한 방법으로 해결해도 좋겠네요

Double은 BigDeciaml 관련 테스트 하다가 실수로 변경하지 못하였습니다.🥲

2024-10-02 06:49 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final BigDecimal roundedLastRank = new BigDecimal(lastRank).setScale(2, RoundingMode.HALF_UP);
통계값을 구하다보면 부동소수점 오차가 발생하여 제거하기 위해서 사용하였습니다.

2024-10-02 06:51 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final Double lastRank = 100.0 - monthlyRanks.stream().mapToDouble(Double::doubleValue).sum();
합치는 로직이 공통으로 쓰인다면 별도의 메서드로 추출해도 좋겠네요

2024-10-02 06:53 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final Double lastRank = 100.0 - monthlyRanks.stream().mapToDouble(Double::doubleValue).sum();
for문을 반대로 사용한 이유는 계산 후 부동 소수점 오차에서 발생한 값들은 "A"랭크 값에 추가적으로 더해주기 위해서 반대에서부터 실행하였습니다. `[A, B, C, D, F]`

2024-10-02 06:54 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyTasksStatisticResponse.java
>          calculate(tasks);
메서드의 반환값을 통해 필드를 각각 초기화 하면 말씀해주신대로 테스트하기에도 더 용이하겠군요 수정해보겠습니다!

2024-10-02 07:12 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
> +        final TaskJpaEntity findTask = tasks.getTaskEntities().get(0);
@kmularise 주신 [코드리뷰](https://github.com/dailyge/dailyge-server/pull/189#discussion_r1779481078)를 보다가 저도 조금 더 상세하게 검증하면 좋지 않을까 하여 수정하였었네요.
아까 구두로 말씀해주신대로 이미 저장 로직을 테스트 한 부분은 있으므로 간단하게 사이즈만 비교하여도 좋겠네요

2024-10-02 07:13 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
> +        final TaskJpaEntity findTask = tasks.getTaskEntities().get(0);
저장 로직을 테스트했다 라기보다 그냥 구체 데이터를 꺼내서 저기서 검증한 것 자체가 좀 애매한 것 같아요.

2024-10-02 07:14 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyTasksStatisticResponse.java
>          calculate(tasks);
중간 과정을 테스트 하려고 하신 것 같은데 좋은 방법일까? 싶네요.

2024-10-02 07:15 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final Double lastRank = 100.0 - monthlyRanks.stream().mapToDouble(Double::doubleValue).sum();
그러면 정순으로 연산하면 안 나오는건가요?

2024-10-02 07:15 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final BigDecimal roundedLastRank = new BigDecimal(lastRank).setScale(2, RoundingMode.HALF_UP);
현재 자릿수를 두 자리까지만 연산하는데 어디서 오차가 발생했을까요?

2024-10-02 07:15 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final BigDecimal roundedLastRank = new BigDecimal(lastRank).setScale(2, RoundingMode.HALF_UP);
아까 구두로 코드까지 설명 드려서 이 부분은 생략할게요.

2024-10-02 07:16 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +    }
아까 구두로 이 부분 정책이랑 다른 내용들 같이 올려달라고 부탁드렸는데, 첨부 해주시겠어요?

2024-10-02 07:19 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
> +        final TaskJpaEntity findTask = tasks.getTaskEntities().get(0);
일급 컬렉션에도 단위 테스트가 있으니 불필요한 테스트겠네요 이해했습니다!

2024-10-02 07:21 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
> +        final TaskJpaEntity findTask = tasks.getTaskEntities().get(0);
애초에 저 클래스 명이 TaskReadIntegrationTest인데 저장 로직을 테스트하는건 말이 안되겠죠?

2024-10-02 07:21 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeeksRateResponse.java
> +        }
현재 로직에서는 빈 배열만 올 수 있으므로 null 체크는 없어도 충분하겠군요 수정하겠습니다.

2024-10-02 07:21 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
> +        final TaskJpaEntity findTask = tasks.getTaskEntities().get(0);
일급 컬렉션에도 단위 테스트가 있다는 말은 무슨 말인가요? 그거랑 전혀 상관 없는 이야기에요.

2024-10-02 07:28 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
> +        final TaskJpaEntity findTask = tasks.getTaskEntities().get(0);
저는 반환되는 객체가 일급컬렉션이므로 해당 객체 안에 데이터도 정합한지 테스트를 하고 싶었던 것 같네요

2024-10-02 08:29 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
> +        final TaskJpaEntity findTask = tasks.getTaskEntities().get(0);
구두로 설명해주신 대로 제가 해당 테스트 목적을 착각했던 것 같네요 기존으로 수정해두겠습니다.

2024-10-02 09:05 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final Double lastRank = 100.0 - monthlyRanks.stream().mapToDouble(Double::doubleValue).sum();
정순으로도 가능합니다. 다만 계산의 편의를 위해 반대서부터 실행하였습니다.

2024-10-02 09:26 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +            rankCounts.set(achievementRank, rankCounts.get(achievementRank) + 1);
현재 Enum의 값으로 해당 인덱스들을 관리하도록 하여 최대한 범위예외가 발생하지 않도록 했지만,

추후 Enum의 Rank 값 추가 등 불가피한 상황이 오면 범위 예외가 발생할 가능성도 있으니 다른 방법을 생각해보겠습니다.

2024-10-02 09:43 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
>          }
Map에 데이터를 넣고 읽을때에는 Key를 직접 작성해주어야 하지 않나요? 제가 말씀해주신 내용의 의도 파악을 못했네요.👀

week는 반영하도록 하겠습니다!

2024-10-02 09:43 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
>          }
Map에 데이터를 넣고 읽을때에는 Key를 직접 작성해주어야 하지 않나요? 제가 말씀해주신 내용의 의도 파악을 못했네요.👀

2024-10-02 09:44 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
>          }
week 좋네요 반영하겠습니다!👍🏻

2024-10-02 10:38 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +    }
한국은 월요일이 주의 시작으로 보기 때문에 [목요일이 포함되어 있는 주](https://digitalchosun.dizzo.com/site/data/html_dir/2018/03/07/2018030711516.html)를 첫번째 주로 간주합니다.
때문에 주차를 구하다 보면 최대 월의 처음과 끝에 최대 3일 가량의 목요일이 포함되지 않은 날들이 발생하게 됩니다.


저는 같은 달의 경우 같은 달의 통계에 속해야한다 생각하여
![image](https://github.com/user-attachments/assets/a3e1ec7c-5bfb-4d9e-ad87-bb6801618eb2)

 - 0주차(목요일이 없는 금,토,일)의 경우 1주차에 포함되도록 하였고, 
 - 마지막 주차(목요일이 없는 월, 화, 수)의 경우는 새로운 주차를 만들도록 하였습니다.

2024-10-02 10:52 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/MonthlyWeekTasksStatisticResponse.java
>          }
이미 구두로 충분히 설명 드린것 같아서 이건 넘어갈게요. 못 찾았으면 그대로 머지하겠습니다.

2024-10-02 11:08 UTC, devjun10 requested changes

2024-10-02 11:08 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskReadIntegrationTest.java
> +        for (TaskJpaEntity taskEntity : tasks.getTaskEntities()) {
final 키워드 또 빠진 것 같네요.

2024-10-02 14:14 UTC, beatmeJY commented
> 그리고 DTO에 로직을 안 넣는 것에 대해 간략히 설명드린 것 같은데, 본인이 생각하기에 일급 컬렉션이 더 좋은 이유에 대해 한 두 문장으로 정리해서 댓글 달아주면 좋을 것 같습니다. 😃

<br/>

`DTO`로 로직을 작성하게 되면 로직들이 중구난방으로 흩어지기 쉬운 반면, `일급 컬렉션`을 사용하게 될 경우 관련 로직들을 한 곳에 모아서 관리 할 수 있게 되어 유지보수와 재사용성이 높아집니다. 특히 초기 서비스 특성 상 요구 사항이 자주 변경되는 환경에서 잘 변경될 수 있는 `DTO`보다 `Entity`를 사용하게 되면 코드의 수정사항도 현저히 줄일 수 있습니다.

2024-10-02 15:14 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +            return new HashMap<>();
해당 반환 값이 수정되지 않는 것이 보장된다면, Collections.emptyMap() 메소드를 사용하는 건 어떨까요?
인스턴스를 매번 생성하지 않고 동일한 정적 인스턴스가 반환되서 메모리 사용량을 조금이나마 줄일 수 있을 거 같아요!

2024-10-02 21:00 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +            return new HashMap<>();
좋네요. 일단 여기까지 반영되면 머지하겠습니다! PR 너무 길어진 것 같아요.

2024-10-02 21:11 UTC, devjun10 commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/TasksUnitTest.java
> +    }
아하. 이거 제가 제목만 보고 판단한 것 같네요. OK!

2024-10-02 21:11 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final Double lastRank = 100.0 - monthlyRanks.stream().mapToDouble(Double::doubleValue).sum();
이렇게 처리할 수도 있네요 ㅋㅋ 재밌게 잘 봤습니다.

2024-10-02 21:12 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +        final BigDecimal roundedLastRank = new BigDecimal(lastRank).setScale(2, RoundingMode.HALF_UP);
이번 주 같이 BigDecimal 공부 해볼까요? 이거 저도 학습할 때, 좀 애매하게 넘어간 부분 있어서 다시 공부해보고 싶었거든요.

2024-10-02 21:12 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/Tasks.java
> +    }
좋네요. 이 부분 정리해서 정책쪽에 넣어두죠!

2024-10-03 06:17 UTC, merged