[DLG-355] 주간 목표 수정 API를 개발한다.
dailyge/dailyge-server pull request #209
Opened 2024-10-09 06:14 UTC by kmularise

## 📝 작업 내용

주간 목표 수정 API를 개발했습니다.

- [X] 주간 목표 수정 API 개발
- [X] 통합 테스트
- [ ] 문서화 테스트

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-355)

2024-10-09 18:31 UTC, devjun10 requested changes

2024-10-10 01:57 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/usecase/WeeklyGoalWriteUseCase.java
> +            throw CommonException.from(INVALID_USER_ID);
좋은 것 같습니다!

2024-10-10 05:24 UTC, beatmeJY reviewed
꼼꼼하네요 문서화 테스트도 기다리고 있을게요!

2024-10-10 06:27 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/usecase/WeeklyGoalWriteUseCase.java
> +            throw CommonException.from(INVALID_USER_ID);
좋은 거 같아요! 그러면 UN_AUTHORIZED로 바꿔둘게요!

2024-10-10 06:32 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/usecase/WeeklyGoalWriteUseCase.java
> +            throw CommonException.from(INVALID_USER_ID);
네 PR 남겨뒀어요!

2024-10-10 06:37 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/persistence/WeeklyGoalReadDao.java
> +    }
해당 부분은 수정 API에서 사용하고 있고 서비스단에서 해당 weeklyGoal 엔티티가 가지는 사용자 아이디와 수정 API를 요청하는 사용자 아이디가 다르면 예외를 던지는 식으로 하고 있습니다. DB 단에서 처리하는게 좋을지 애플리케이션에서 처리하는 게 좋을지 고민 중에 있습니다! @devjun10 님은 어떻게 생각하시나요?

2024-10-10 07:06 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/request/WeeklyGoalStatusUpdateRequest.java
> +    Boolean done
null 값도 들어올 수 있다고 해서 래퍼 타입을 사용했습니다. 다시 생각해보니 null값을 허용하지 않는게 나을 거 같아서 원시 타입으로 바꾸도록 할게요!

2024-10-11 02:46 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/persistence/WeeklyGoalReadDao.java
> +    }
애플리케이션에서 코드로 제어하면 어떨까요?

2024-10-11 02:48 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/usecase/WeeklyGoalWriteUseCase.java
> +            throw CommonException.from(INVALID_USER_ID);
@beatmeJY @kmularise 그러면 INVALID_USER_ID는 삭제하고 UN_AUTHORIZED 하나로만 가죠!

2024-10-11 02:52 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/persistence/WeeklyGoalReadDao.java
> +    }
그러면 수정 API랑 삭제 API에서는 현재처럼 애플리케이션에서 코드로 제어하도록 할게요! 생각해보니 UnAuthorized 구분할려면 애플리케이션에서 제어하는게 맞는 거 같아요!

2024-10-11 02:59 UTC, beatmeJY approved these changes
이번 주간 목표 수정 API 개발도 고생하셨습니다!

2024-10-11 03:55 UTC, devjun10 approved these changes
수고하셨어요~

2024-10-11 03:55 UTC, merged