[DLG-360] 주간 목표 조회 API를 개발한다.
dailyge/dailyge-server pull request #212
Opened 2024-10-11 09:12 UTC by kmularise

## 📝 작업 내용

주간 목표 조회 API를 개발했습니다.

- [ ] 주간 목표 조회 커서 페이징
- [ ] 주간 목표 조회 통합 테스트
- [ ] 주간 목표 조회 문서화 테스트

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-360)

2024-10-15 02:58 UTC, kmularise commented on dailyge-api/src/test/java/project/dailyge/app/common/DatabaseTestBase.java
> +    protected LocalDate now = LocalDate.now();
현재에는 DatabaseTestBase 상에서 null값으로 되어 있어서요. 테스트를 할 때마다 now에 새로운 LocalDate.now()를 하는식으로 바꾸면 될까요?

2024-10-15 02:59 UTC, kmularise commented on dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/integrationtest/WeeklyGoalReadIntegrationTest.java
> +    private static final String DEFAULT_TITLE = "주간 목표 조회 API 개발";
네 수정할게요!

2024-10-15 03:00 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/validator/WeeklyGoalValidator.java
> +        if (!weekStartDate.getDayOfWeek().equals(DayOfWeek.MONDAY)) {
유효성 검증이라 클라이언트 측에서 검증하고 프레젠테이션 계층에서 검증하는 것으로 바꿀게요!

2024-10-15 03:01 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/weeklygoal/WeeklyGoalEntityReadRepository.java
> +    List<WeeklyGoalJpaEntity> findByCursor(Long userId, long index, int limit, LocalDateTime weekStartDate);
지금 현재 Cusor라는 클래스가 dailyge-api 모듈에 속해 있어서 일단은 이렇게 해뒀습니다! Cursor가 storage 모듈에 속해 있는 것으로 바꾸는 것으로 합의되면 수정하도록 할게요!

2024-10-15 03:03 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/weeklygoal/WeeklyGoalEntityReadRepository.java
> +    List<WeeklyGoalJpaEntity> findByCursor(Long userId, long index, int limit, LocalDateTime weekStartDate);
그런 이유라면 지금처럼 하셔도 좋을 것 같네요~!

2024-10-15 03:04 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/common/DatabaseTestBase.java
> +    protected LocalDate now = LocalDate.now();
그렇죠. 각 테스트들이 멱등성을 가지게 하면 좋을 것 같네요.

2024-10-15 03:04 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/validator/WeeklyGoalValidator.java
> +        if (!weekStartDate.getDayOfWeek().equals(DayOfWeek.MONDAY)) {
넵. 저희 Client측 Validator는 **`${DOMAIN}ClientValidator`** 잊지 마세요 ㅎㅎ

2024-10-15 03:13 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/validator/WeeklyGoalValidator.java
> +        if (!weekStartDate.getDayOfWeek().equals(DayOfWeek.MONDAY)) {
네 맞습니다. 수정하도록 할게요!

2024-10-15 03:13 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/WeeklyGoalReadApi.java
> +            .findPageByCursor(dailygeUser, cursor, weekStartDate.atTime(0, 0, 0, 0))
좋은 의견입니다! 한곳에서 수정하도록 할게요!

2024-10-15 03:19 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/persistence/WeeklyGoalReadDao.java
> +            .orderBy(weeklyGoalJpaEntity.createdAt.asc())
애플리케이션에서 정렬을 하게 되면 데이터베이스에서 해당 조건을 만족하는 데이터들을 모두 가져온 다음 Java에 내장된 정렬함수를 이용해서 정렬을 하게 됩니다.

이렇게 되면 해당 조건을 만족하는 데이터가 많이 있을 경우, 해당 조건을 만족하는 데이터를 모두 메모리에 로드하기 때문에 메모리를 너무 많이 사용하게 된다고 생각합니다. 하지만 해당 조건을 만족하는 데이터가 적은 경우에는 애플리케이션에서 정렬하는 것도 괜찮다고 생각합니다.

현재에는 주간 목표의 개수에 대해서 제한을 두지 않았기 때문에 애플리케이션에서 정렬을 하는 것은 데이터가 많은 경우에 메모리를 많이 사용할 수 있을 것 같다고 생각이 들어서 데이터베이스에서 인덱스를 통해 정렬 후, 해당 조건을 만족하는 데이터를 가져오는 것이 괜찮다는 생각입니다. 

 이에 대해 @devjun10 님께서는 어떻게 생각하시나요?

2024-10-15 04:08 UTC, beatmeJY reviewed
제가 쉬고 오는 동안 @devjun10 님께서 너무 꼼꼼하게 코드리뷰를 잘해주셨네요👍🏻
좋은 PR과 코드리뷰 잘보았습니다 고생하셨어요👍🏻

2024-10-15 04:13 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/response/WeeklyGoalResponse.java
> +    private final LocalDate startWeekDate;
여기에선 `LocalDate`를 사용하신 이유가 있으실까요?👀

2024-10-15 04:18 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/integrationtest/WeeklyGoalReadIntegrationTest.java
> +        assertEquals(1, findWeeklyGoals.size());
테스트 케이스 굳!👍🏻적당히 개행이 있어도 좋을 것 같네요!

2024-10-15 05:35 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/persistence/WeeklyGoalReadDao.java
> +            .orderBy(weeklyGoalJpaEntity.createdAt.asc())
이거 아까 구두로 설명드려서 원하는대로 수정해보시죠~

2024-10-15 09:26 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/response/WeeklyGoalResponse.java
> +    private final LocalDate startWeekDate;
각 주간 목표에서 기준으로 삼고 있는 주간 시작 날짜(월요일)을 나타내기 위해 사용했습니다!

2024-10-15 09:26 UTC, kmularise commented on dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/integrationtest/WeeklyGoalReadIntegrationTest.java
> +        assertEquals(1, findWeeklyGoals.size());
좋아요! 적당히 개행을 추가해보도록 할게요!

2024-10-16 07:44 UTC, beatmeJY approved these changes
고생하셨습니다!

2024-10-16 09:39 UTC, devjun10 requested changes
저희 fix는 버그를 수정할 때 사용하는데, 이건 단순 코드 수정 아닌가요?

2024-10-16 09:39 UTC, devjun10 commented on dailyge-api/build.gradle
> -
감사합니다 ㅎㅎ

2024-10-16 09:40 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/unittest/WeeklyGoalClientValidatorUnitTest.java
> +    private WeeklyGoalClientValidator weeklyGoalClientValidator;
이것도 한 칸 개행 컨벤션!

2024-10-17 01:58 UTC, kmularise commented on dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/unittest/WeeklyGoalClientValidatorUnitTest.java
> +    private WeeklyGoalClientValidator weeklyGoalClientValidator;
수정할게요!

2024-10-17 02:09 UTC, kmularise commented
태그를 잘못사용했었네요. 머지할때 수정해두면 되겠죠?

2024-10-17 02:31 UTC, devjun10 commented
> 태그를 잘못사용했었네요. 머지할때 수정해두면 되겠죠?

아니에요. 굳이 수정 안하셔도 되고, 이전에 fix 표기된 PR 있는데, 그것만 좀 바꿔주세요.

2024-10-17 08:04 UTC, devjun10 approved these changes
수고하셨습니다

2024-10-17 08:04 UTC, merged