[DLG-361] 회고 조회 시 전체페이지 개수를 추가한다.
dailyge/dailyge-server pull request #213
Opened 2024-10-15 04:32 UTC by beatmeJY

## 📝 작업 내용

제가 이전 회고 페이징 조회 API에 클라이언트에서 필요한 전체 페이징 개수도 포함 하였어야 하는데 실수로 놓쳤기에 추가하였습니다.

- [X] 회고 조회 시 전체 페이지 개수 추가
- [X] 테스트 작성

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-361)

2024-10-15 04:51 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
> +    }
이거 totalCount를 비동기로 같이 찾아오는거 어떨까요? 아까 구두로 설명드린 방식으로 개선하면 비동기로 결과를 조합해서 빠르게 가져올 수 있거든요.

2024-10-15 05:23 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
> +    }
즉, totalCount랑 데이터를 비동기로 동시에 가져오는거죠. 

```java
public class Main {
    public static void main(String[] args) throws ExecutionException, InterruptedException {
        CompletableFuture.runAsync(() -> {

        });
        final CompletableFuture<String> dataA = CompletableFuture.supplyAsync(() -> {
            try {
                System.out.println("A START");
                System.out.println("TotalCount Fetching");
            } catch (Exception ex) {

            }
            return "A END";
        });

        final CompletableFuture<String> dataB = CompletableFuture.supplyAsync(() -> {
            try {
                System.out.println("B START");
                System.out.println("Data Fetching");
            } catch (Exception ex) {

            }
            return "B END";
        });

        CompletableFuture<Void> result = CompletableFuture.allOf(dataA, dataB);
        result.get();
    }
}
```

2024-10-15 05:24 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
> +    }
이 부분에서 비동기 예외처리가 중요한데, 학습하고 별도 PR이나 Discussion에 정리해주세요~

2024-10-15 05:24 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
> +    }
그리고 한계점도 존재하는데, 이 부분도 학습하고 알려주세요~

2024-10-15 05:25 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
> +    }
아까 잠깐 모여서 보여주신 예제 코드이군요 감사합니다! 반영해보겠습니다!😄

2024-10-15 05:28 UTC, kmularise reviewed
전체페이지 개수가 추가되었군요! 고생하셨습니다 :)

2024-10-15 05:28 UTC, kmularise commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        return (int) Math.ceil((double) totalCount / limit);
totalCount가 0보다 작으면 어떻게 되나요? 
double로 형변환을 하지 않아도 전체 페이지 개수를 반환할 수 있지 않을까요?

2024-10-15 05:43 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        return (int) Math.ceil((double) totalCount / limit);
말씀해주신대로 0보다 작은 음수일 경우 음수를 반환하지만 현재 설계 상 `totalCount`의 값은 DB에서 회고의 개수를 쿼리하여 읽어오기 때문에 0 또는 양수만 넘어올 수 있습니다.

2024-10-15 05:44 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        return (int) Math.ceil((double) totalCount / limit);
double 형 변환이 없이 페이징을 하는 방법을 서칭하여 보았는데 괜찮은 것 같네요! 
Math 패키지를 사용하지 않고도 할 수 있어 수정해서 코드로 올려두어 보겠습니다!👍🏻

2024-10-15 05:50 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        return (int) Math.ceil((double) totalCount / limit);
double 형 변환이 없이 페이징을 하는 방법을 서칭하여 보았는데 좋은 것 같네요!👍🏻
Math 패키지를 사용하지 않고도 할 수 있어 성능적으로 훨 좋을 것 같아 수정해서 코드로 올려두어 보겠습니다!

2024-10-16 09:37 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
+1 하신 이유가 있나요?

2024-10-16 09:37 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
음..? 페이징 계산 공식 설명좀 해주시겠어요?

2024-10-16 10:50 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
limit가 10이라고 가정하였을때,
totalCount가 10인 경우 -1을 해서 `9/10`이 되어 `0.9`가 나오게 되는데 이는 `int`형의 경우 소수점을 버리기 때문에 `0`이 되며,
이후 무조건적으로 +1을 더하기에 전체 페이지의 크기는 1이 됩니다.

이러한 방식으로 `int`를 `int`로 나눌 경우 나머지 값이 존재하는 경우엔 **모두 버려지게 되는데** 이를 이용하여 무조건 적으로 **1을 더해줌**으로써 실수형으로도 빠르게 전체 페이지를 구할 수 있게 됩니다.

2024-10-16 10:52 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
ㅋㅋ 메서드명 때문에 좀 헷깔렸던 것 같은데 그냥 전체 페이지 수를 구하는거죠?

2024-10-16 10:53 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
그렇다면 왜 limit으로 나누신거에요? 사용자가 보낸 한 페이지에서 볼 갯수 만큼 나누어야 하지 않나요?

2024-10-16 10:53 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
네 맞습니다! 전체 페이지 수를 구하는 메서드입니다

2024-10-16 10:53 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
limit가 한 페이지에서 볼 수 있는 개수를 나타냅니다!

2024-10-16 10:54 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
즉, 사용자가 한 페이지에 10개씩 보고 싶다고 하면 20개를 기준으로 페이지를 나누고, 30개를 한 페이지에서 보고 싶다하면 30개를 기준으로 페이지를 나눠야 하잖아요?

2024-10-16 10:55 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
그렇다면 pagePerCount나 조금 더 명확한 이름을 사용하면 어떨까요?

2024-10-16 10:55 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
네! 그렇게 설계 되어있습니다

2024-10-16 10:58 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
전체 페이지 수를 구하는 공식인데 pagePerCount는 페이지 당 개수를 의미하지 않나요?👀

2024-10-16 11:00 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
**`(전체 게시물 수 / 페이지 별 보여주는 개수)`** 하면 전체 페이지 수가 나오겠죠? 그러면 저기서 페이지 별 보여주는 개수를 pagePerCount로 변수명을 바꾸는거죠. 지금은 변수명이 limit으로 돼 있는데, 저것만 보고 왜 limit으로 나누지? limit은 제한하는 값 아닌가? 싶었네요.

2024-10-16 11:01 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
아하 limit 변수명을 바꾸라 하신거군요 좋습니다!👍🏻

2024-10-16 11:02 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
반드시 바꾸는게 아니라 어떤지 여쭤본거였어요. 왜 limit으로 하신지 이해가 잘 안되거든요.

2024-10-16 11:04 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
페이지 수를 제한한다고 생각하여 limit으로 하였는데 pagePerCount도 좋은 변수명인 것 같아서 수정하겠습니다!😄

2024-10-16 11:10 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
참고로 스프링이 제공해주는 [PageRequest](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/PageRequest.html)는 다음과 같은 변수명을 사용하고 있습니다.

2024-10-16 11:10 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
토탈 카운트가 0인 경우 데이터가 없는 것이라 계산 공식 결과 값도 0으로 나오게 됩니다

2024-10-16 11:13 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
음..? 이렇게 돌려보니까 1이 나오네요? 

```java
class TotalCountUnitTest {

    @Test
    void totalCountTest() {
        assertEquals(0, getTotalPageCount(0));      // 실패. 1 나옴.
    }

    public static int getTotalPageCount(final int totalCount) {
        return (totalCount - 1) / 10 + 1;
    }
}
```

2024-10-16 13:14 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
아 제가 착각했네요 0이 올 경우는 0이 나오도록 수정해두겠습니다!

2024-10-17 02:28 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
구두로 이야기한대로 반영가시죠!

2024-10-17 02:52 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
좋습니다! 나중에 까먹을 것 같아서 한 번 정리해 두겠습니다!

`totalCount`가 0이 올 경우 `pageSize`가 1보다 크면 항상 1이 반환되어서 클라이언트에서 처리에 용이하도록 현재 로직은 유지하되, `pageSize`는 최소 5보다 크게 설정할 수 있도록 유효성을 검증하는 로직을 만들어두겠습니다!

2024-10-17 03:34 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
최소 5보다 크게 설정하는 것도 좋지만, 5, 10, 20, 30과 같이 확실하게 사용자가 입력된 값만 보낼 수 있도록 **`제한`** 하는게 조금 더 좋을 것 같은데, 어떻게 생각하시나요?

2024-10-17 03:46 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
저는 일단 제한을 둘 필요까지는 없다고 생각이 드는게, 각 사용자의 화면 크기나 상태에 따라 6개, 8개와 같이 요청하는 경우도 있을 수 있을 것 같아서 조금 더 프리하게 열어두는게 좋지 않을까 라는 생각이 드네요

2024-10-17 03:55 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
왜 유동적인 값들을 허용하려고 하시는거에요? 운영하는 서비스들 보면, 5개, 10개, 15개, 20개 이렇게 제한을 두는데 저 값들을 사용자가 직접 입력하게 하는게 필요할까요?

2024-10-17 03:57 UTC, devjun10 requested changes

2024-10-17 03:57 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
> +            .limit(page.getPageSize())
이거는 의사결정이 들어간 코드 변경인데, 왜 style로 수정한거에요?

2024-10-17 03:57 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        final Integer pageNumber,
왜 pageNumber를 원시 값이 아닌 Integer로 하신거에요?

2024-10-17 03:58 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        return (pageNumber - 1) * pageSize;
위에서는 Integer로 사용했는데 여기서는 반환 값을 원시 값으로 반환하는 이유가 있나요?

2024-10-17 04:10 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
>      }
페이지 UI에 따라 4개씩 보여주는게 예쁠수도 있고 한데 너무 타이트하게 서버에서 막아두면 그 때마다 서버의 코드와 테스트를 수정하여 주어야하기 때문에 개발에 불필요한 코스트가 발생하지 않을까 했습니다👀

2024-10-17 05:06 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
> +            .limit(page.getPageSize())
이전에 이야기 했던 내용을 수정한거라 refactor로 했어야겠네요! 다음에는 주의하겠습니다!

2024-10-17 05:28 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        return (pageNumber - 1) * pageSize;
계산한 결과는 항상 값이 발생하기 때문에 원시 값을 사용하여도 괜찮을 것 같다고 생각하였습니다.

2024-10-17 05:32 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        final Integer pageNumber,
별 의미는 없었지만 null이 발생할 수 없는 상황이므로 래퍼클래스보다 원시 값을 사용하는 측이 더 좋겠네요!

2024-10-17 07:24 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        final Integer pageNumber,
null 값이 오면 당연히 방어를 해줘야 하는데, 별 의미가 없다는게 무슨 말인가요?

2024-10-17 07:24 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        return (pageNumber - 1) * pageSize;
default size를 정해뒀다는 거죠?

2024-10-17 07:31 UTC, devjun10 requested changes

2024-10-17 07:31 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
>  }
fetchOne은 null을 반환할 수도 있기 때문에 검증이 필요하지 않나요? 이런식으로요.

```java
public long findTotalCount(final Long userId) {
    Long count = jpaQueryFactory
        .select(retrospectJpaEntity.id.count())
        .from(retrospectJpaEntity)
        .where(
            retrospectJpaEntity.userId.eq(userId)
                .and(retrospectJpaEntity.deleted.eq(false))
        )
        .fetchOne();
    return count != null ? count : 0L;
}
```

2024-10-17 07:31 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
>  }
그리고 단순한 count 쿼리라면 QueryDSL말고 JdbcTemplate을 쓰는 것도 고려해볼만한데, 이 방식은 어떨까요?

2024-10-17 07:33 UTC, beatmeJY commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        return (pageNumber - 1) * pageSize;
아닙니다 해당 연산 결과는 어떠한 값이 오더라도 최소 1이상을 반환하기 때문에 별도의 size를 설정하여 두진 않았습니다.

2024-10-17 07:37 UTC, devjun10 requested changes

2024-10-17 07:37 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/presentation/RetrospectReadApi.java
> +        return ApiResponse.from(OK, payloadFuture.join());
우선 해보라고는 했지만, 컨트롤러에 이렇게 로직이 들어가는게 맞나? 하는 생각이 먼저 드는데요, Repository에서 별도의 객체를 만들어서 totalCount와 데이터(List<Entity>)를 한 번에 가져온 후 반환하면 어떨까? 하는 생각이 들어서요. 사용해보셔서 아시겠지만 코드가 지저분해지거든요. 그리고 ignored은 왜 사용하신건가요? 보통 그 값의 결과를 사용하지 않으면 언더바(_)를 사용하는데, 왜 ignore를 사용하신거에요?

2024-10-17 07:39 UTC, devjun10 requested changes

2024-10-17 07:40 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
>  }
IDE가 경고만 봐도 NPE가 발생할 것 같네요. 

<img width="1036" alt="스크린샷 2024-10-17 오후 4 40 05" src="https://github.com/user-attachments/assets/9bfdb849-b1a6-43c4-8864-1b7eb6bb7a27">

2024-10-17 07:41 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
>  }
fetchOne API 명세를 보면 @Nullable이 명시 돼 있네요.

```java
public abstract class AbstractJPAQuery<T, Q extends AbstractJPAQuery<T, Q>> extends JPAQueryBase<T, Q> {
    
    ......

    public @Nullable T fetchOne() throws NonUniqueResultException {
        Object var2;
        try {
            Query query = this.createQuery(this.getMetadata().getModifiers(), false);
            var2 = this.getSingleResult(query);
            return var2;
        } catch (NoResultException var7) {
            logger.log(Level.FINEST, var7.getMessage(), var7);
            var2 = null;
        } catch (jakarta.persistence.NonUniqueResultException var8) {
            throw new NonUniqueResultException(var8);
        } finally {
            this.reset();
        }

        return var2;
    }

    ......

```

2024-10-17 07:42 UTC, devjun10 commented on support/src/main/java/project/dailyge/app/page/CustomPageable.java
> +        final Integer pageNumber,
코드를 작성했는데 별 의미가 없이 사용했다면 문제가 있지 않을까요?

2024-10-17 07:46 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/presentation/RetrospectReadApi.java
> +                throw RetrospectTypeException.from(RETROSPECT_UN_RESOLVED_EXCEPTION);
저는 Database의 예외 정도가 발생할 것 같다 생각하였습니다. 다만 현재 로직이 컨트롤러 계층에 존재하여서 `DATA_ACCESS_EXCEPTION`과 같은 데이터베이스 예외를 던지는 것은 맞지 않는다 생각하여 `UN_RESOLVED_EXCEPTION`에러와 함께 메세지를 담아주었는데 @devjun10님께서는 어떠하게 생각하시나요?

2024-10-17 07:47 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/presentation/RetrospectReadApi.java
> +                throw RetrospectTypeException.from(RETROSPECT_UN_RESOLVED_EXCEPTION);
그래서 위에  데이터베이스에서 한 번에 찾아오는게 어떤지에 대해 물었습니다.

2024-10-17 07:55 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
>  }
말씀해주신대로 fetchOne의 경우는 null이 발생할 수는 있습니다.

하지만 확인 해본 결과 SQL 쿼리는 정상적으로 count 쿼리가 날라가게 됩니다.
![image](https://github.com/user-attachments/assets/f4d67f1e-017e-42d6-81b3-3c4aa5fe9c72)

![image](https://github.com/user-attachments/assets/403dd4af-1bbf-408d-a8ee-c3eaba62a3dd)

때문에 실제로 동작을 하여 보면 null이 아닌 정상적으로 0의 결과값이 돌아오는 것을 확인 할 수 있고 위의 SQL에서는 null이 발생할 수 없기 때문에 추가적인 검증이 필요하진 않을 것 같습니다.

> 제 IDE에서는 신기하게 위의 에러가 안나네요.👀 IDE 에러가 맞을 때도 있지만 맞지 않을때도 있는 것 같습니다.

2024-10-17 08:03 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
>  }
결과 자체는 count( ) 때문에 NPE가 발생 안하는데, API 명세보면 @Nullable이 있기 때문에 API 명세를 따르는게 좋지 않을까요?

2024-10-17 08:25 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
>  }
말씀대로 API 명세 따르는 것은 좋은 것 같습니다!

2024-10-17 08:41 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/presentation/RetrospectReadApi.java
> +        return ApiResponse.from(OK, payloadFuture.join());
코틀린에서 _를 사용했는데, 자바 17은 안되는걸 몰랐네요. 하나 배워갑니다!

2024-10-17 08:47 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java
>  }
좋은 것 같습니다 JdbcTemplate로 한번 변경해보겠습니다!

2024-10-17 08:53 UTC, merged

2024-10-18 02:11 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/retrospect/presentation/RetrospectReadApi.java
> +        return ApiResponse.from(OK, payloadFuture.join());
저도 개발하면서 컨트롤러에 로직이 길어지는건 별로라고 생각하였었는데 Repository에서 별도의 객체를 만드는건 좋은 것 같네요 다음 PR에서 바로 리팩토링 해보겠습니다!