[DLG-372] 구직 활동 관리 테이블을 설계한다.
dailyge/dailyge-server pull request #223
Opened 2024-11-01 04:48 UTC by beatmeJY

## 📝 작업 내용

이번에는 구직 활동 관리 테이블을 설계해보았습니다.

우선 구직 활동 관리 테이블 설계 시 하나의 테이블로 설계하려고 했지만, 
어제 구두로 회사 테이블이 추후 다른곳에서도 사용 가능할 것 같다는 결론 나와 총 2개의 테이블로 구성해 보았습니다.

- [x] 회사, 구직활동 테이블 설계

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-372)

2024-11-01 05:09 UTC, kmularise reviewed
구직활동 테이블 설계 확인했습니다!

2024-11-01 05:09 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
요구 역량들인거 같은데 String으로 저장되는 이유가 있나요?

2024-11-01 05:09 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/CompanySize.java
> +    SMALL_ENTERPRISE("중소기업"),
스타트업과 유니콘 기업, 중소기업의 분류 기준은 어떻게 되나요?  기획적인 부분이지만 스타트업, 유니콘 기업등을 고려한다면 시리즈 투자 정보를 따로 빼는 것도 괜찮을 거 같아요!

2024-11-01 05:11 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
하나의 공고에 몇십까지 공고 스택들이 있을 수 있어 해당 기술들을 하나하나 선택하여 입력하기에는 사용자의 부담이 커질 것 같아 기술 스택들을 복사 후 붙여넣기 할 수 있도록 하고자 하였습니다.

2024-11-01 05:47 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPostingStatus.java
> +    PREPARING_PERSONALITY_TEST("인적서 준비 중"),
그냥 서류 작성, 코딩 테스트 이런식으로 하는게 더 깔끔하지 않을까요?

2024-11-01 05:48 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
왜 이 필드가 있나요?

2024-11-01 05:48 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/CompanySize.java
> +    SMALL_ENTERPRISE("중소기업"),
스타트업, 유니콘 기업 분류 기준이 뭔가요?

2024-11-01 05:51 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/CompanySize.java
> +    SMALL_ENTERPRISE("중소기업"),
아직 확고한 기준은 세워야 하고 일단은 필요할 것 같은 이넘 값을 구상해 보았었습니다.

2024-11-01 05:54 UTC, devjun10 requested changes

2024-11-01 05:54 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPostingStatus.java
> +    PERSONALITY_TEST_REJECTED("인적성 탈락");
면접 탈락에 대한 필드가 빠진 것 같아요.

2024-11-01 05:54 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/NeededDocumentType.java
> +    BLOG("블로그");
이건 왜 넣으신건가요?

2024-11-01 05:55 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
![image](https://github.com/user-attachments/assets/42c0b4de-10a8-4cc6-beaa-a2e707375264)
저는 이전에 예시로 이런식으로 공고들을 관리하고 있었는데 있다면 한눈에 파악하기 쉬울 것 같아서 넣어 보았었습니다.

2024-11-01 05:56 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/NeededDocumentType.java
> +    BLOG("블로그");
![image](https://github.com/user-attachments/assets/a6f59ac3-bb97-4465-93f9-653077f00215)
해당 건도 마찬가지로 어떤 서류들이 필요한지 정리해둘 떄 유용할 것 같아 넣었었습니다.

2024-11-01 05:57 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPostingStatus.java
> +    PREPARING_PERSONALITY_TEST("인적서 준비 중"),
두 의견 모두 반영하겠습니다.

2024-11-01 05:58 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/Company.java
> +public class Company extends BaseEntity {
name이 복수 형태가 아니네요.

2024-11-01 05:58 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/Company.java
> +    private CompanySize companySize;
companySize? 기업 형태(Type/CompanyType)이 조금 더 적절하지 않을까요?

2024-11-01 06:00 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
링크가 있는데 그냥 지원 현황이나 이런 상태만 보여주고 저런건 직접 보는게 빠르지 않을까요?

2024-11-01 06:02 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/NeededDocumentType.java
> +    BLOG("블로그");
만드는 이 테이블이 서류 지원/접수 이런 현황을 파악하는 테이블 아니었나요? 

> 그리고 그 와중에 지원동기는 왜 들어가 있나요?

2024-11-01 06:04 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/Company.java
> +public class Company extends BaseEntity {
그리고 회사 설명이나 추가로 활용할 필드가 더 필요할 것 같은데, 너무 정보가 없는거 아닌가요?

2024-11-01 06:07 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/Company.java
> +    private CompanySize companySize;
`company_type` 으로 수정해보겠습니다!

2024-11-01 06:09 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/NeededDocumentType.java
> +    BLOG("블로그");
공고 서치 하여 접수 전의 공고들도 볼 수 있기 때문에 어느 서류가 필요한지도 포함하면 좋을 것 같다고 생각하였습니다.

회사마다 이력서만 제출할 수 있는 곳이 있으며 지원동기도 묻는 곳이 있어 이런 것도 표기해두면 서류 제출 시 시간 배분을 더 유용하게 할 수 있을 것 같다 생각하여 추가하였습니다.

2024-11-01 06:11 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
Null을 허용할 예정이라 필요 없다면 사용하지 않아도 되고, 비고란 특이사항을 기입해두면 빠르게 파악하기 쉬워 용이하지 않을까요?

2024-11-01 06:15 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
애초에 저 필드가 왜 있는건가요? 그냥 지원 현황 파악하려고 만든 테이블 아니었나요?

2024-11-01 06:17 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/NeededDocumentType.java
> +    BLOG("블로그");
이런거 다 넣으면 가로로 얼마나 길어지나요? 고려해보고 필드 넣으신걸까요? 

> 현재 필드만 해도 가로로 얼마나 길어질지 가늠이 잘 안돼서요.

2024-11-01 06:18 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/Company.java
> +public class Company extends BaseEntity {
현재 구직 활동 관리 기능에는 회사 설명까진 필요하진 않을 것 같은데 만약 나중에 필요한 경우 추가 하는게 맞지 않을까요?

> 사용자가 구직 활동 시 회사를 입력할 때 회사 설명이 필요하거나 따로 입력하진 않기 때문입니다.👀

2024-11-01 06:26 UTC, devjun10 requested changes

2024-11-01 06:26 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
이거 지원 현황 정도가 맞지 않나요? 그리고 이 내용이 2024-상/하반기 이런식으로 구분 돼야 할 것 같은데, 어떻게 생각하시나요?

2024-11-01 06:32 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/NeededDocumentType.java
> +    BLOG("블로그");
가로 스크롤을 사용하며 컬럼의 크기와 순서도 조정이 가능한 웹 페이지를 생각했었습니다.

> 사용자 판단에 따라 필요 없는 컬럼을 맨 뒤로 보내면 됨

2024-11-01 06:34 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
저 역시도 노션에서 현재 위와 같은 기능들을 사용하고 있어 단순하게 지원 현황만 파악하는 것에는 차별화된 장점이 없기 때문에 제가 사용하는 기능들을 최대한 한번 의견을 내어보았습니다.🥲

2024-11-01 06:36 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
상반기 하반기! 좋은거 같긴하네요. 그럼 연도와 분기 컬럼도 추가해볼까요?

2024-11-01 06:40 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
연도와 월별로 구분하는 것도 좋을 거 같아요!

2024-11-01 07:01 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
우선은 초기 버전은 빼고 심플하게 작업해봐도 좋을 것 같네요!

2024-11-01 08:31 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +    private String requiredSkills;
넵. 일단 심플하게 가고 나중에 수정합시다요~

2024-11-01 08:33 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
칼럼도 좋은데, 별도 테이블이면 더 좋지 않을까 싶어요. 인덱스 잡을 수도 있고. 이 부분은 한 번 고려해보시죠!

2024-11-04 04:08 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
저는 연도와 월별로 복합 인덱스를 잡아도 빠르지 않을까 싶은데 이부분은 같이 이야기 해봐도 재밌겠네요!👀

2024-11-04 07:27 UTC, merged

2024-11-05 14:48 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
연도와 월은 카디널리티가 높은 것도 아닌데 왜 두 칼럼으로 복합 인덱스를 잡나요?

2024-11-06 05:09 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
제가 처음에 생각했던 방법은 `사용자-연도-월` 순으로 인덱스를 잡는 것을 생각하였습니다.

**같은 테이블에 연도와 월을 포함하는 경우의 장점**
 * **직관적인 쿼리 작성**: 상반기, 하반기, 또는 특정 연도별 제출 이력을 조회하는 경우, 연도와 월 컬럼을 메인 테이블에 포함하면 `WHERE` 조건에 간단히 연도와 월을 지정해 직관적으로 작성할 수 있습니다.
 * **효율적인 인덱스 활용**: 유저-연도-월 복합 인덱스를 설정할 경우, 유저-연도로 검색할 때도 인덱스가 유용하게 동작해 효율적인 검색이 가능합니다.
 * **간소화 된 구조**: 별도 테이블 없이 단일 테이블에서 데이터를 관리하므로 구조가 간단해지고, 조인 없이 조회할 수 있어 성능 최적화에 유리합니다.

**별도 테이블에 연도와 월을 분리하는 경우의 단점**
* **쿼리의 복잡성 증가**: 연도와 월을 별도 테이블로 두는 경우, 특정 기간의 제출 이력을 조회하려면 해당 기간의 월을 먼저 조회하고, 이를 이용해 `IN` 조건으로 필터링하는 등 쿼리가 복잡해 질 수 있습니다.
* **조인 비용**: 한번의 쿼리로 해결 시 매 조회 시마다 연도와 월 테이블을 `JOIN`해야 합니다.
* **인덱스의 비효율**: 유저-연도 또는 연도-월 단위의 조건으로 조회 시, 별도 테이블을 두면 복합 인덱스가 제공하는 효율을 놓칠 가능성이 있습니다.

따라서 연도와 월을 같은 테이블에 포함시키면, 조회하는 패턴에 맞춰 간단하고 유동적인 쿼리 작성이 가능하고, 복합 인덱스도 충분히 활용 가능해 마찬가지로 빠른 검색이 가능하다 생각하였습니다.

2024-11-06 05:26 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
저는 우선 `사용자-연도-월` 순으로 인덱스를 잡는 것을 생각하였습니다. 이유는 지원 이력을 볼 때에는 해당 월의 공고만 보기보다 해당 연도 또는 최근 몇달의 공고를 한번에 보는 경우가 더 많을 것 같다고 생각하였습니다.

**같은 테이블에 연도와 월을 포함하는 경우의 장점**
 * **직관적인 쿼리 작성**: 상반기, 하반기, 또는 특정 연도별 제출 이력을 조회하는 경우, 연도와 월 컬럼을 메인 테이블에 포함하면 `WHERE` 조건에 간단히 연도와 월을 지정해 직관적으로 작성할 수 있습니다.
 * **효율적인 인덱스 활용**: `유저-연도-월` 복합 인덱스를 설정할 경우, `유저-연도`로 검색할 때도 인덱스가 유용하게 동작해 효율적인 검색이 가능합니다.
 * **간소화 된 구조**: 별도 테이블 없이 단일 테이블에서 데이터를 관리하므로 구조가 간단해지고, 조인 없이 조회할 수 있어 성능 최적화에 유리합니다.

**별도 테이블에 연도와 월을 분리하는 경우의 단점**
* **쿼리의 복잡성 증가**: 연도와 월을 별도 테이블로 두는 경우, 특정 기간의 제출 이력을 조회하려면 해당 기간의 월을 먼저 조회하고, 이를 이용해 `IN` 조건으로 필터링하는 등 쿼리가 복잡해 질 수 있습니다.
* **조인 비용**: 한번의 쿼리로 해결 시 매 조회 시마다 연도와 월 테이블을 `JOIN`해야 합니다.
* **범위 조회 효율**: 연간 등 범위 조회 시 별도 테이블을 두는 것보다 `유저-연도` 복합 인덱스가 제공하는 효율이 더 높다 생각하였습니다.

물론 별도의 테이블로 두면 하나의 키로 인덱싱이 빠르다는 것은 이해하였지만, 복합 인덱스는 좀 더 직관적이고 충분히 빠르게 검색이 가능하다 생각하였습니다.

2024-11-06 05:48 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
윗쪽에는 **`사용자-년도-월`** 중 사용자가 빠져서 질문했네요. 넘어가겠습니다. 

> 그리고 년/상반기, 년/하반기, 년/수시채용으로 구분하는데 굳이 월을 사용할 필요가 있을까요?

2024-11-06 06:45 UTC, beatmeJY commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
저도 찾아보니 현O오O에버 채용 등은 월 단위로 존재할 때가 있어서 조금 더 구체적으로 나누어야 할 것 같았어요!

2024-11-06 21:14 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/jobposting/JobPosting.java
> +public class JobPosting extends BaseEntity {
하나씩 맞춰가는 과정이 조금 더디지만, 계속 맞춰가면서 나중엔 핑하면 퐁 하고 바로 올 수 있도록 해보죠~!!