[DLG-373] 쪽지 삭제 API를 개발한다.
dailyge/dailyge-server pull request #224
Opened 2024-11-01 08:15 UTC by devjun10

## 📝 작업 내용

쪽지 삭제 API를 개발했습니다. 

- [x] 쪽지 삭제 API 개발
- [x] 쪽지 엔티티 수신자/발신자 deleted 칼럼 추가 
- [x] schema.sql 파일 수정
- [x] 쪽지 삭제 단위, 통합, 문서화 테스트 작성

<br/><br/>

쪽지 전송 시, 한 데이터 row를 수신자/발신자가 **`같이`** 사용하고 있습니다. 다른 경우는 문제가 없지만, 쪽지함에서 데이터를 **`삭제`** 했을 때 문제가 발생합니다. 예를 들어, 발신자가 쪽지를 삭제했을 때, deleted 칼럼을 true로 하면 수신자도 이를 조회할 수 없게 되는 것이죠. 따라서 이를 해결하기 위해 발신자, 수신자가 삭제를 마킹하는 칼럼을 별도로 둬서 이를 처리하려고 했습니다.

```kotlin
@Entity(name = "notes")
class NoteJpaEntity(
    ......
) : BaseEntity() {

    @Column(name = "sender_deleted")
    private var _senderDeleted: Boolean = false

    @Column(name = "receiver_deleted")
    private var _receiverDeleted: Boolean = false

    ......

}
```

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-373)

2024-11-01 08:25 UTC, beatmeJY commented on storage/rdb/src/main/kotlin/project/dailyge/entity/note/NoteJpaEntity.kt
> +    }
그럼 이제 쪽지에선 기존의 `deleted`는 필요 없지 않을까요?

2024-11-01 08:25 UTC, beatmeJY commented on storage/rdb/src/main/kotlin/project/dailyge/entity/note/NoteJpaEntity.kt
> +        get() = _receiverDeleted
한쪽에서 삭제 시 같이 보지 못하는 건 미처 생각 못했었는데 좋네요👍🏻

2024-11-01 08:27 UTC, devjun10 commented on storage/rdb/src/main/kotlin/project/dailyge/entity/note/NoteJpaEntity.kt
> +    }
넵. 불필요하긴 한데, 운영칼럼이라 최대한 사용하려고 양쪽 모두 쪽지를 삭제했을 때, 값을 변경했습니다.

2024-11-01 08:31 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/note/persistence/NoteReadDao.java
> +    }
여기선 주석이 오히려 헷갈리는 거 같아요

2024-11-01 08:37 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/note/application/usecase/NoteWriteUseCase.java
> +    }
여기있는 주석은 오히려 헷갈리는거 같아요!

2024-11-01 08:38 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/note/application/usecase/NoteWriteUseCase.java
> +    }
제 실수네요. 수정해뒀습니다~!

2024-11-01 08:39 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/note/persistence/NoteReadDao.java
> +                .fetchOne());
여기있는 주석은 오히려 헷갈리는거 같아요

2024-11-01 08:41 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/note/persistence/NoteReadDao.java
> +                .fetchOne());
제 실수네요. 수정해뒀습니다~!

2024-11-01 08:42 UTC, beatmeJY approved these changes
잘 보았습니다. 삭제 시 발신자와 수신자가 같은 쪽지 레코드를 바라보고 있으니 delete 컬럼이 별도로 필요하겠네요. 고생하셨습니다!👍🏻

2024-11-01 08:48 UTC, kmularise approved these changes
쪽지 삭제 확인했습니다! deleted 컬럼 등 궁금했던 부분이 이미 pr이 달려있네요. 고생하셨습니다:)

2024-11-01 08:51 UTC, beatmeJY requested changes
아직 문서화 테스트 작성이 덜 되었는데 실수로 approve 해서 좀 더 기다릴게요

2024-11-05 22:18 UTC, dailyge-dev approved these changes

2024-11-06 03:26 UTC, kmularise approved these changes
고생하셨습니다:)

2024-11-06 03:26 UTC, kmularise commented on .github/workflows/dailyge-api-ci.yaml
> +        run: ./gradlew :dailyge-api:koverXmlReport sonar -PskipJib=true -Dsonar.inclusions=**/dailyge-api/**,**/storage/**
이 옵션은 무엇인가요?

2024-11-06 03:29 UTC, merged