[DLG-369] 반복일정 등록 API를 개발한다.
dailyge/dailyge-server pull request #225
Opened 2024-11-01 09:31 UTC by kmularise

## 📝 작업 내용

반복일정 등록 API를 개발했습니다.

- [X] 일간, 주간, 월간 반복일정 등록 API 개발 
- [ ] 단위, 통합 테스트 작성
- [ ] 문서화 테스트 작성

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-369)

2024-11-01 09:32 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/application/command/TaskRecurrenceCreateCommand.java
> +public record TaskRecurrenceCreateCommand(
toString이 빠져있네요!

2024-11-01 09:33 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskRecurrenceWriteUseCase.java
> +    }
이 부분 로직이 복잡한 것 같은데, [일급 컬렉션](https://en.wikipedia.org/wiki/First-class_citizen)을 사용해보는 것은 어떨까요?

> 일급 컬렉션을 사용해서 로직을 내부로 감추면, 호출 부에서는 메서드 하나만 호출하면 되고, 로직이 객체 내부에 있기 때문에 테스트 하기가 용이해져요.

2024-11-01 09:33 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskRecurrenceWriteUseCase.java
> +            TaskJpaEntity newTask = new TaskJpaEntity(
final 키워드!

2024-11-01 09:33 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/requesst/TaskRecurrenceCreateRequest.java
> +public class TaskRecurrenceCreateRequest {
toString 재정의 해주셔요~

2024-11-01 09:34 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskRecurrenceWriteUseCase.java
> +            TaskJpaEntity newTask = new TaskJpaEntity(
final이 빠졌네요

2024-11-01 09:36 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/utils/ScheduleUtils.java
> +public final class ScheduleUtils {
유틸 클래스에 final 키워드는 좋은 것 같아요. 어차피 상속할 필요가 없으니까. 추가로 **`private 생성자를 리플렉션으로 호출`** 하는 것을 방어해보면 어떨까요? Java의 **`Objects`** 내부 구현을 보면 유틸 클래스를 어떻게 생성하는지 볼 수 있어요. 한 번 참조해보세요.

```java
public final class Objects {
    private Objects() {
        throw new AssertionError("No java.util.Objects instances for you!");
    }
```

2024-11-01 09:38 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/DatePattern.java
> +public class DatePattern {
이 클래스는 어떤 역할을 하나요? 👀

2024-11-01 09:42 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskRecurrenceWriteUseCase.java
> +        if (taskRecurrence.getRecurrenceType().equals(RecurrenceType.WEEKLY)) {
비교할 때, **`expected.equals(actual)`** 이렇게 하면 어떨까요? **`Junit의 equals 메서드`** 내부 구현을 보더라도 expected가 앞에 나오는데, 한 번 참조해보셔요.

```java
public class Assertions {

    ......

    public static void assertEquals(short expected, short actual) {
        AssertEquals.assertEquals(expected, actual);
    }

    public static void assertEquals(short expected, Short actual) {
        AssertEquals.assertEquals(expected, actual);
    }

    public static void assertEquals(Short expected, short actual) {
        AssertEquals.assertEquals(expected, actual);
    }

    ......
```

2024-11-01 09:44 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/utils/ScheduleUtils.java
> +        LocalDateTime currentDate = startDate;
final이 빠져있네요!

2024-11-01 09:49 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/utils/ScheduleUtils.java
> +            int lastDayOfMonth = yearMonth.lengthOfMonth();
`currentDate`랑 `lastDayOfMonth`에 final이 빠져있네요

2024-11-04 01:57 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/requesst/TaskRecurrenceCreateRequest.java
> +public class TaskRecurrenceCreateRequest {
수정할게요!

2024-11-04 01:57 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskRecurrenceWriteUseCase.java
> +    }
네 좋은 의견입니다! 적용해볼게요!

2024-11-04 01:58 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/utils/ScheduleUtils.java
> +public final class ScheduleUtils {
유틸 클래스를 사용하지 않을 수도 있어서 추후에 유틸클래스를 사용하게 된다면 반영하겠습니다!

2024-11-04 01:59 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/task/DatePattern.java
> +public class DatePattern {
dayPattern을 유효성을 검증하고자 했습니다. 이 부분도 ClientValidator로 빼서 수정하게 될 것 같습니다.

2024-11-04 02:17 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskRecurrenceWriteUseCase.java
> +            TaskJpaEntity newTask = new TaskJpaEntity(
수정할게요!

2024-11-04 02:17 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/application/command/TaskRecurrenceCreateCommand.java
> +public record TaskRecurrenceCreateCommand(
수정할게요!

2024-11-04 02:18 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskRecurrenceWriteUseCase.java
> +        if (taskRecurrence.getRecurrenceType().equals(RecurrenceType.WEEKLY)) {
네 이부분도 수정하겠습니다!

2024-11-04 02:19 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/utils/ScheduleUtils.java
> +        LocalDateTime currentDate = startDate;
이부분은 재할당이 되서 final을 의도적으로 뺐습니다!

2024-11-04 02:20 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/utils/ScheduleUtils.java
> +            int lastDayOfMonth = yearMonth.lengthOfMonth();
currentDate는 재할당이 되서 의도적으로 final을 뺐습니다. `lastDayOfMonth`는 수정하도록 할게요!

2024-11-05 09:34 UTC, devjun10 requested changes

2024-11-05 09:34 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/RecurrenceTasks.java
> +    }
이건 궁금해서 여쭤봐요. LocalDateTime.plusMonth가 있는데, 이걸 활용 안 하신 이유가 있을까요?

2024-11-05 09:34 UTC, devjun10 commented on storage/rdb/src/main/java/project/dailyge/entity/task/RecurrenceTasks.java
> +    }
계산로직이 많이 복잡한데, plusDays(7) 같은 자바 API를 활용하면 개발자가 하는 것 보다 더 정확하게 계산해줄 것 같은데, 왜 이렇게 처리하신지 궁금해요.

2024-11-05 09:35 UTC, devjun10 requested changes

2024-11-05 09:35 UTC, devjun10 commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/RecurrenceTasksUnitTest.java
> +class RecurrenceTasksUnitTest {
테스트에 경계 값을 최대한 다양하게 넣으면 좋지 않을까요? 로직이 많이 복잡한데 ㅎㅎ

2024-11-06 04:36 UTC, kmularise commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/RecurrenceTasksUnitTest.java
> +class RecurrenceTasksUnitTest {
네 좀 더 추가해보도록 할게요!

2024-11-06 04:39 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/task/RecurrenceTasks.java
> +    }
기존에는 월마다 복수 일 수(매월 1일, 30일, 31일)을 반복하게끔 했었는데요. 말일에 대해서 고려하다보니 복잡해진거 같습니다. 구글 캘린더 참고해보니 월간 복수 날짜 지정은, 매주 수요일 반복, 둘째주 수요일 반복 이런식으로 대체가 가능할거 같아서 월간 반복 같은 경우에는 날짜를 하나만 지정할 수 있게끔 바꾸고 그에 따라 로직도 좀 더 간단히 하는식으로 리팩토링할거 같습니다!

2024-11-06 04:40 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/task/RecurrenceTasks.java
> +            if (taskRecurrence.getDatePattern().contains(currentDayOfWeek.getValue())) {
네 좋은 의견이에요! 적용해서 리팩토링 할게요!

2024-11-06 04:46 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/task/RecurrenceTasks.java
> +) {
객체 내부에서 공통적으로 유지하는 성질을 추려봤을 때, 저정도로 나와서 인자를 많이 받게 되었습니다!

2024-11-06 09:54 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceCreateDocumentationTest.java
> +            List.of(8),
잘 작성해주셨네요!👍🏻 별 건 아니지만, 어느 파라미터가 잘 못 되었는지 한눈에 파악하기가 어려웠는데, 올바르지 않는 값을 적절한 변수명으로 생성해서 넣어주셔도 좋을 것 같아요! (`List.of(invalidWeeksDay)`)

2024-11-06 09:57 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceCreateDocumentationTest.java
> +        );
잘 작성해주셨네요!👍🏻 
이건 반영해 주시지 않아도 좋습니다! 어느 파라미터가 잘 못 되었는지 한번에 파악하기가 어려웠는데, 올바르지 않는 값을 적절한 변수명으로 생성해서 넣어주시는 것도 좋을 것 같아요. ex) `List.of(invalidWeeksDay)`

2024-11-06 09:58 UTC, devjun10 requested changes

2024-11-06 09:58 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/validator/TaskRecurrenceClientValidator.java
> +        return dayPattern != null && dayPattern.size() == 1 && isBetween(dayPattern, FIRST_DAY, LAST_DAY);
&& 면 개행하는게 어떨까요?

2024-11-06 10:02 UTC, devjun10 commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/RecurrenceTasksUnitTest.java
> +    Map<YearMonth, Long> createMonthlyTaskMap(LocalDate startDate, LocalDate endDate) {
여기도 final 및 규칙이 적용 안 됐네요~!

2024-11-06 10:03 UTC, devjun10 requested changes

2024-11-06 10:03 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskRecurrenceCreateIntegrationTest.java
> +    }
실패 케이스는 없나요?

2024-11-06 10:03 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskRecurrenceCreateIntegrationTest.java
> +    }
실패 케이스는 없나요?

2024-11-07 02:08 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/task/RecurrenceTasks.java
> +        return !scheduleDate.isBefore(taskRecurrence.getStartDate()) && !scheduleDate.isAfter(taskRecurrence.getEndDate());
넵 반영할게요!

2024-11-07 02:11 UTC, kmularise commented on dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskRecurrenceCreateIntegrationTest.java
> +    }
우선은 입력값에 대한 실패케이스는 clientValidator나 RecurrenceTasks 단위테스트에 검증을 해서 따로 기재를 하진 않았던 거 같아요!

2024-11-07 02:14 UTC, kmularise commented on storage/rdb/src/test/java/project/dailyge/entity/test/task/RecurrenceTasksUnitTest.java
> +    Map<YearMonth, Long> createMonthlyTaskMap(LocalDate startDate, LocalDate endDate) {
이후 커밋에서 수정해두었어요!

2024-11-07 02:32 UTC, kmularise commented on storage/rdb/src/main/java/project/dailyge/entity/task/RecurrenceTasks.java
> +        return Math.min(recurrenceDay, lastDayOfMonth);
PR에 반영해둘게요!

2024-11-07 02:38 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/validator/TaskRecurrenceClientValidator.java
> +        return dayPattern != null && dayPattern.size() == 1 && isBetween(dayPattern, FIRST_DAY, LAST_DAY);
반영할게요!

2024-11-07 02:43 UTC, kmularise commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceCreateDocumentationTest.java
> +        );
좋은 의견이에요! 반영할게요!

2024-11-07 03:22 UTC, devjun10 approved these changes

2024-11-07 03:26 UTC, beatmeJY approved these changes
반복일정 복잡했을텐데 고생하셨습니다!

2024-11-07 03:26 UTC, merged