[DLG-381] 반복 일정 조회 API를 개발한다.
dailyge/dailyge-server pull request #233
Opened 2024-11-08 05:52 UTC by kmularise

## 📝 작업 내용

반복 일정 조회 API를 개발합니다.

- [X] 태스크 조회 API 수정
- [ ] 사용자의 반복 일정 조회 API 개발
- [ ] 통합테스트, 문서화테스트

<br/><br/>

## 🔗 이슈 트래킹
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-381)

2024-11-12 04:33 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceReadDocumentationTest.java
> +    }
Command는 다른 곳에서도 사용할 것 같은데, 별도의 클래스(Fixture)로 분리하면 어떨까요?

2024-11-12 04:34 UTC, devjun10 commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskRecurrenceUpdateApi.java
> +        @Valid @RequestBody final TaskRecurrenceUpdateRequest request
어떤 버그가 있었나요?

2024-11-12 04:34 UTC, kmularise commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceReadDocumentationTest.java
> +    }
네 Fixture로 분리해볼게요!

2024-11-12 04:36 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskRecurrenceUpdateApi.java
> +        @Valid @RequestBody final TaskRecurrenceUpdateRequest request
API에 정상적을 요청이 도달하지 않는 점을 문서화테스트를 통해 확인할 수 있었습니다!

2024-11-12 04:40 UTC, devjun10 requested changes
SonarCloud 이슈가 있는 것 같은데, 저 부분도 같이 수정해주세요~

2024-11-12 04:48 UTC, beatmeJY commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskRecurrenceReadApi.java
> +    @GetMapping(path = {"/task-recurrences"})
여기서 `task-recurrences`도 클래스 매핑 path에 공통으로 넣어도 좋을 것 같네요

2024-11-12 04:49 UTC, kmularise commented on dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskRecurrenceReadApi.java
> +    @GetMapping(path = {"/task-recurrences"})
수정할게요!

2024-11-12 04:54 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceReadDocumentationTest.java
> +class TaskRecurrenceReadDocumentationTest extends DatabaseTestBase {
실패 케이스도 있으면 좋을 것 같아요!

2024-11-12 04:57 UTC, devjun10 commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceReadDocumentationTest.java
> +class TaskRecurrenceReadDocumentationTest extends DatabaseTestBase {
목록조회는 굳이 필요없지 않을까요?

2024-11-12 04:59 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceReadDocumentationTest.java
> +class TaskRecurrenceReadDocumentationTest extends DatabaseTestBase {
클래스명도 수정 부탁드릴게요!

2024-11-13 03:37 UTC, kmularise commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceReadDocumentationTest.java
> +class TaskRecurrenceReadDocumentationTest extends DatabaseTestBase {
조회 부분이라 실패 케이스가 특별히 없는 거 같아서 실패케이스는 추가하지 않았어요! 클래스명은 수정했어요!

2024-11-13 03:42 UTC, beatmeJY approved these changes

2024-11-13 03:42 UTC, beatmeJY commented on dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceReadDocumentationTest.java
> +class TaskRecurrenceReadDocumentationTest extends DatabaseTestBase {
ㅎㅎ 조회였군요 좋습니다!👍🏻

2024-11-13 03:58 UTC, beatmeJY commented
반복일정 복잡했을텐데 고생하셨습니다!👍🏻

2024-11-13 05:15 UTC, devjun10 approved these changes
수고하셨습니다.

2024-11-13 05:15 UTC, merged